// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Alert } from '../../components/DataDisplay';

const meta = {
  title: "Data Display/Alert",
  component: Alert,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "Status": {
    "control": "inline-radio",
    "options": [
      "Info",
      "Success",
      "Warning",
      "Error"
    ],
    "description": "Figma variant property `Status`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Info"
      }
    }
  },
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "New lab results are available"
      }
    }
  },
  "Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Two results were added to the patient record."
      }
    }
  },
  "Show Action": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Close": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Status": "Info", "Title": "New lab results are available", "Message": "Two results were added to the patient record.", "Show Action": false, "Show Close": true},
  parameters: {
    figma: { name: "Alert", page: "➜ Banners, Badges & Toasts", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4196" },
    docs: { description: { component: "**Figma:** `Alert` on page `➜ Banners, Badges & Toasts` (Data Display). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4196)\n\n**Tier:** Molecule\n\n**Use:** Inline message that stays until resolved (expiring insurance, missing consent, failed sync).\n\n**Figma description:**\n\n> Molecule (Icon, text, Button Link atom, Icon Button atom). Purpose: an inline message inside a page or form that stays until resolved (expiring insurance, missing consent, failed sync).  \n> Usage rules: place above the content it refers to; Status matches meaning; Title states the fact, Message says what to do; Show Action for one follow-up link; Show Close only when the message can be dismissed. Status components use status tokens, never button tokens.  \n> Accessibility: status text on its status background is at least 4.5:1; icon + title carry the meaning, not color; role=\"status\" (or \"alert\" for Error) in code.  \n\n**When to use:** expiring insurance, missing consent, failed sync, error summary at the top of a form, server error on sign in.\n\n**When not to use:** short confirmation after an action (**Toast**); a decision that blocks the page (**Modal**); a status word on a record (**Badge**).\n\n**Built from:** `Icon/Info`, `Icon/Check Circle`, `Icon/Warning`, `Icon/Alert Circle`, `Button`, `Icon Button`, `Icon/Close`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Alert>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Info: Story = { name: "Info", args: { "Status": "Info" } };
export const Success: Story = { name: "Success", args: { "Status": "Success" } };
export const Warning: Story = { name: "Warning", args: { "Status": "Warning" } };
export const Error: Story = { name: "Error", args: { "Status": "Error" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Info", "Success", "Warning", "Error"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Status={x}</div>
          <Alert {...args} {...{ "Status": x } as any} />
        </div>
      ))}
    </div>
  ),
};
