// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Avatar } from '../../components/DataDisplay';

const meta = {
  title: "Data Display/Avatar",
  component: Avatar,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Initials",
      "Icon"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Initials"
      }
    }
  },
  "Size": {
    "control": "select",
    "options": [
      "24",
      "32",
      "40",
      "60",
      "100"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "24"
      }
    }
  },
  "Initials": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "AS"
      }
    }
  },
  "Show Status": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  }
},
  args: {"Type": "Initials", "Size": "24", "Initials": "AS", "Show Status": false},
  parameters: {
    figma: { name: "Avatar", page: "➜ Avatars & Upload Image", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-3023" },
    docs: { description: { component: "**Figma:** `Avatar` on page `➜ Avatars & Upload Image` (Data Display). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-3023)\n\n**Tier:** Atom\n\n**Use:** Identify a person; Initials when there is no photo, Icon for unknown people.\n\n**Figma description:**\n\n> Atom. Purpose: identify a person (patient, doctor, staff) in lists, headers, appointments and comments.  \n> Usage rules: Initials (first + last name, 2 letters) when there is no photo; Icon for unknown or anonymous people; sizes 24 (dense tables), 32 (lists), 40 (headers), 60 (profile cards), 100 (profile page). Show Status for online / available doctors only. A Photo type (image fill) is still to add, see gaps.  \n> Accessibility: initials text on bg/brand uses color/text/on-brand (5.6:1); in code the avatar needs the person's name as alt text; the status dot must also be described in text (\"Available\").  \n\n**When to use:** patient and doctor rows (32), dense tables (24), the signed-in user in the Top Bar (40), profile cards (60), profile page (100).\n\n**When not to use:** for things that are not people (an `Icon/*`); as a button by itself (wrap it in a labelled button when it opens a menu).\n\n**Built from:** `Icon/User`\n\n**Known Figma gaps (see gaps.md):** no Photo type (accepted gap)\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Initials: Story = { name: "Initials", args: { "Type": "Initials" } };
export const Icon: Story = { name: "Icon", args: { "Type": "Icon" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Initials", "Icon"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["24", "32", "40", "60", "100"].map((y) => <Avatar key={y} {...args} {...{ "Type": x, "Size": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
