// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Badge } from '../../components/DataDisplay';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Data Display/Badge",
  component: Badge,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Status": {
    "control": "select",
    "options": [
      "Info",
      "Success",
      "Warning",
      "Error",
      "Neutral"
    ],
    "description": "Figma variant property `Status`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Info"
      }
    }
  },
  "Size": {
    "control": "inline-radio",
    "options": [
      "sm",
      "md"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "sm"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Confirmed"
      }
    }
  },
  "Show Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Info"
      }
    }
  }
},
  args: {"Status": "Info", "Size": "sm", "Label": "Confirmed", "Show Icon": false, "Icon": "Icon/Info"},
  parameters: {
    figma: { name: "Badge", page: "➜ Banners, Badges & Toasts", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2921" },
    docs: { description: { component: "**Figma:** `Badge` on page `➜ Banners, Badges & Toasts` (Data Display). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2921)\n\n**Tier:** Atom\n\n**Use:** Short status word on a record (Confirmed, Pending, Cancelled, New, Draft).\n\n**Figma description:**\n\n> Atom. Purpose: short status label on a record (appointment Confirmed / Pending / Cancelled, lab result New, invoice Draft).  \n> Usage rules: one or two words; status color matches meaning (Success confirmed/paid, Warning pending/needs review, Error cancelled/overdue, Info new/informational, Neutral draft/archived); never use a Badge as a button; do not use brand/button tokens for status. Show Icon when the badge must be readable without color.  \n> Accessibility: status text on its status background is at least 4.5:1 (e.g. text/success on bg/success); sm is 20px high, md 24px; meaning must also be in the text, never color alone.  \n\n**When to use:** appointment status (Confirmed, Pending, Cancelled), lab result New, invoice Draft or Overdue, counts in Sidebar / Item.\n\n**When not to use:** as a button or filter (**Button**, **Tabs / Bar** Segmented); for sentences (**Alert**); for a person (**Avatar**).\n\n**Built from:** `Icon/*`\n\n**Known Figma gaps (see gaps.md):** Label default \"Confirmed\" shows on every Status; override it\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Info: Story = { name: "Info", args: { "Status": "Info" } };
export const Success: Story = { name: "Success", args: { "Status": "Success" } };
export const Warning: Story = { name: "Warning", args: { "Status": "Warning" } };
export const Error: Story = { name: "Error", args: { "Status": "Error" } };
export const Neutral: Story = { name: "Neutral", args: { "Status": "Neutral" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Info", "Success", "Warning", "Error", "Neutral"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Status={x}</div>
          <div className="sb-row">{["sm", "md"].map((y) => <Badge key={y} {...args} {...{ "Status": x, "Size": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
