// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Modal, ModalInUse } from '../../components/DataDisplay';

const meta = {
  title: "Data Display/Modal",
  component: Modal,
  tags: ['!autodocs', 'tier-organism'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Danger"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Reschedule appointment"
      }
    }
  },
  "Body": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Choose a new date and time. The patient will get an SMS with the new details."
      }
    }
  },
  "Show Content": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Show Close": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Type": "Default", "Title": "Reschedule appointment", "Body": "Choose a new date and time. The patient will get an SMS with the new details.", "Show Content": true, "Show Close": true},
  parameters: {
    figma: { name: "Modal", page: "➜ Popups", tier: "Organism", order: 3 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=9-4751" },
    docs: { description: { component: "**Figma:** `Modal` on page `➜ Popups` (Data Display). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=9-4751)\n\n**Tier:** Organism\n\n**Use:** Focused task or confirmation over the page (reschedule a visit, confirm cancelling an appointment).\n\n**Figma description:**\n\n> Organism (Icon Button, Button atoms, Input / Date and Select / Dropdown in the content slot, exposed actions). Purpose: a focused task or confirmation over the page (reschedule a visit, confirm cancelling an appointment, delete a record).  \n> Usage rules: Default for short tasks with a few fields; Danger to confirm destructive actions, with the consequence in the body and a Danger primary button that names the action; buttons right-aligned, secondary first; put forms longer than 5 fields on a page instead; show over the scrim color/bg/overlay.  \n> Accessibility: 480px wide, radius/2xl, shadow-xl; focus moves into the modal and is trapped, Escape and Close dismiss (not for Danger in progress); title is the accessible name (aria-labelledby); body text color/text/secondary 11:1.  \n\n**When to use:** reschedule a visit (Default with content), confirm a destructive action (Danger: \"Cancel this appointment?\" with \"Keep appointment\" and \"Cancel appointment\").\n\n**When not to use:** information without a decision (**Alert**, **Toast**); forms longer than 5 fields (a page); stacked on another Modal.\n\n**Built from:** `Icon Button`, `Icon/Close`, `Icon/Warning`, `Button`, `Input / Date`, `Select / Dropdown`\n\n**Known Figma gaps (see gaps.md):** Type=Danger shows the Default title; override it\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Modal>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "Type": "Default" } };
export const Danger: Story = { name: "Danger", args: { "Type": "Danger" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Danger"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <Modal {...args} {...{ "Type": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <ModalInUse /> };
