// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Toast, ToastInUse } from '../../components/DataDisplay';

const meta = {
  title: "Data Display/Toast",
  component: Toast,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "Status": {
    "control": "inline-radio",
    "options": [
      "Info",
      "Success",
      "Warning",
      "Error"
    ],
    "description": "Figma variant property `Status`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Info"
      }
    }
  },
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Appointment confirmed"
      }
    }
  },
  "Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "A confirmation was sent to the patient by SMS."
      }
    }
  },
  "Show Action": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Close": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Status": "Info", "Title": "Appointment confirmed", "Message": "A confirmation was sent to the patient by SMS.", "Show Action": false, "Show Close": true},
  parameters: {
    figma: { name: "Toast", page: "➜ Banners, Badges & Toasts", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4271" },
    docs: { description: { component: "**Figma:** `Toast` on page `➜ Banners, Badges & Toasts` (Data Display). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4271)\n\n**Tier:** Molecule\n\n**Use:** Short temporary confirmation or error after an action; bottom-right.\n\n**Figma description:**\n\n> Molecule (Icon, text, Button Link atom, Icon Button atom). Purpose: a short, temporary confirmation or error after an action (appointment saved, message sent, upload failed).  \n> Usage rules: bottom-right on desktop, top on mobile; auto-hide after 5 s except Error; one toast at a time; Show Action for Undo or View; never use a toast for information the user must act on (use Alert or a Modal).  \n> Accessibility: raised surface bg/subtle with shadow-lg; text/primary 13:1; announced with role=\"status\" (Error: role=\"alert\") in code; Close Icon Button has aria-label.  \n\n**When to use:** appointment saved, message sent, upload failed, Undo after a delete (Show Action).\n\n**When not to use:** information the user must act on (**Alert** or **Modal**).\n\n**Built from:** `Icon/Info`, `Icon/Check Circle`, `Icon/Warning`, `Icon/Alert Circle`, `Button`, `Icon Button`, `Icon/Close`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Toast>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Info: Story = { name: "Info", args: { "Status": "Info" } };
export const Success: Story = { name: "Success", args: { "Status": "Success" } };
export const Warning: Story = { name: "Warning", args: { "Status": "Warning" } };
export const Error: Story = { name: "Error", args: { "Status": "Error" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Info", "Success", "Warning", "Error"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Status={x}</div>
          <Toast {...args} {...{ "Status": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <ToastInUse /> };
