// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Tooltip, TooltipInUse } from '../../components/DataDisplay';

const meta = {
  title: "Data Display/Tooltip",
  component: Tooltip,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Arrow": {
    "control": "inline-radio",
    "options": [
      "Up",
      "Down",
      "Left",
      "Right"
    ],
    "description": "Figma variant property `Arrow`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Up"
      }
    }
  },
  "Size": {
    "control": "inline-radio",
    "options": [
      "Small",
      "Large"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Small"
      }
    }
  },
  "Text": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Edit appointment"
      }
    }
  },
  "Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Fasting required"
      }
    }
  }
},
  args: {"Arrow": "Up", "Size": "Small", "Text": "Edit appointment", "Title": "Fasting required"},
  parameters: {
    figma: { name: "Tooltip", page: "➜ Tooltips", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3098" },
    docs: { description: { component: "**Figma:** `Tooltip` on page `➜ Tooltips` (Data Display). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3098)\n\n**Tier:** Atom\n\n**Use:** Short hint on hover or focus; Small names an action, Large = title + body.\n\n**Figma description:**\n\n> Atom. Purpose: a short hint on hover or focus (name of an Icon Button, meaning of a status, preparation note for a lab test).  \n> Usage rules: Small = one line naming an action or value; Large = title + up to two sentences. Never put links, buttons or required information only in a tooltip; the arrow points at the trigger. Light surface (bg/inverse) so it stands out on the dark UI.  \n> Accessibility: text/inverse on bg/inverse is above 15:1; shows on hover and keyboard focus, hides on Escape; trigger references it with aria-describedby in code.  \n\n**When to use:** the name of every Icon Button, the meaning of a Badge, a lab test preparation note (Large).\n\n**When not to use:** for required information, links or buttons (Hint, **Alert**, **Modal**); as the only explanation on touch screens.\n\n**Known Figma gaps (see gaps.md):** Large shows the Small default text as its body; override it\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Tooltip>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Up: Story = { name: "Up", args: { "Arrow": "Up" } };
export const Down: Story = { name: "Down", args: { "Arrow": "Down" } };
export const Left: Story = { name: "Left", args: { "Arrow": "Left" } };
export const Right: Story = { name: "Right", args: { "Arrow": "Right" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Small", "Large"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Size={x}</div>
          <div className="sb-row">{["Up", "Down", "Left", "Right"].map((y) => <Tooltip key={y} {...args} {...{ "Size": x, "Arrow": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <TooltipInUse /> };
