// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { BreadcrumbItem } from '../../components/Navigation';

const meta = {
  title: "Navigation/Breadcrumb / Item",
  component: BreadcrumbItem,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Current",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Patients"
      }
    }
  },
  "Show Separator": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Patients", "Show Separator": true},
  parameters: {
    figma: { name: "Breadcrumb / Item", page: "➜ Pagination, Tabs & Breadcrumb", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3196" },
    docs: { description: { component: "**Figma:** `Breadcrumb / Item` on page `➜ Pagination, Tabs & Breadcrumb` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3196)\n\n**Tier:** Atom\n\n**Use:** One level of the page path inside Breadcrumb; last level Current with no separator.\n\n**Figma description:**\n\n> Atom. Purpose: one level of the page path (Patients > Amira Saleh > Visit 12 Mar).  \n> Usage rules: only inside Breadcrumb; every level except the last is a link; the last is Current with Show Separator off; keep labels short (truncate names in code).  \n> Accessibility: links use color/text/link (brand/400, 9:1 on bg/primary); Current has aria-current=\"page\"; separators are decorative (aria-hidden) in code.  \n\n**When to use:** only inside **Breadcrumb**.\n\n**When not to use:** alone.\n\n**Built from:** `Icon/Chevron Right`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof BreadcrumbItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Current: Story = { name: "Current", args: { "State": "Current" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Current", "Focus", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <BreadcrumbItem {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Current", "Focus", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <BreadcrumbItem {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
