// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Breadcrumb } from '../../components/Navigation';

const meta = {
  title: "Navigation/Breadcrumb",
  component: Breadcrumb,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {},
  args: {},
  parameters: {
    figma: { name: "Breadcrumb", page: "➜ Pagination, Tabs & Breadcrumb", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4354" },
    docs: { description: { component: "**Figma:** `Breadcrumb` on page `➜ Pagination, Tabs & Breadcrumb` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4354)\n\n**Tier:** Molecule\n\n**Use:** Page path on pages two or more levels deep; never the main navigation.\n\n**Figma description:**\n\n> Molecule (Breadcrumb / Item atoms, exposed). Purpose: show where the page sits and link back to parent pages (Patients > Amira Saleh > Visit 12 Mar).  \n> Usage rules: use on pages two or more levels deep; the last level is Current without a separator; hide middle levels on mobile; never use it as the main navigation.  \n> Accessibility: nav with aria-label=\"Breadcrumb\"; links 9:1 on bg/primary; last item aria-current=\"page\".  \n\n**When to use:** detail pages two or more levels deep (patient record, visit, invoice).\n\n**When not to use:** as main navigation (**Sidebar**); on top-level pages.\n\n**Built from:** `Breadcrumb / Item`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Breadcrumb>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
