// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Button } from '../../components/Navigation';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Navigation/Button",
  component: Button,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "select",
    "options": [
      "Filled",
      "Pill",
      "Outline",
      "Link",
      "Danger"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Filled"
      }
    }
  },
  "Size": {
    "control": "select",
    "options": [
      "xs",
      "sm",
      "base",
      "lg",
      "xl"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "xs"
      }
    }
  },
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Pressed",
      "Focus",
      "Disabled",
      "Loading"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Button"
      }
    }
  },
  "Show Leading Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Trailing Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Leading Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Add"
      }
    }
  },
  "Trailing Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Arrow Right"
      }
    }
  }
},
  args: {"Type": "Filled", "Size": "xs", "State": "Default", "Label": "Button", "Show Leading Icon": false, "Show Trailing Icon": false, "Leading Icon": "Icon/Add", "Trailing Icon": "Icon/Arrow Right"},
  parameters: {
    figma: { name: "Button", page: "➜ Buttons & Links", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=4-2308" },
    docs: { description: { component: "**Figma:** `Button` on page `➜ Buttons & Links` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=4-2308)\n\n**Tier:** Atom\n\n**Use:** Actions. One Filled/Pill per view; Outline secondary; Link inline; Danger destructive behind a Modal. Sizes xs 32, sm 36, base 40, lg 48, xl 56.\n\n**Figma description:**\n\n> Atom. Purpose: triggers an action (save, book, submit) or, as Type=Link, a light inline action.  \n> Usage rules: one Filled (or Pill) button per view for the main action; Outline for secondary actions; Link for low-emphasis inline actions; Danger only for destructive actions (delete patient record, cancel appointment) and always behind a confirmation. Use Loading while the action runs and keep the label. Do not use a Button to navigate between pages (use Link text or navigation components) and never use Danger for non-destructive actions.  \n> Accessibility: minimum size 32px (xs) and 40px (base) for primary actions; label text on filled green is color/action/primary/text (gray/950, 5.6:1); Focus shows the focus-ring-offset effect; Disabled uses opacity/disabled and must not be the only way to explain why an action is unavailable.  \n\n**When to use:** Save changes, Book appointment, New appointment (Top Bar), Sign in; Cancel (Outline); Forgot password, View all (Link); Delete record (Danger, behind a Modal).\n\n**When not to use:** to move between pages (**Sidebar / Item**, **Breadcrumb**, **Tabs / Item**, a link); icon-only actions (**Icon Button**); Danger on a non-destructive action.\n\n**Built from:** `Icon/*`, `Icon/Loader`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Filled: Story = { name: "Filled", args: { "Type": "Filled" } };
export const Pill: Story = { name: "Pill", args: { "Type": "Pill" } };
export const Outline: Story = { name: "Outline", args: { "Type": "Outline" } };
export const Link: Story = { name: "Link", args: { "Type": "Link" } };
export const Danger: Story = { name: "Danger", args: { "Type": "Danger" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StatePressed: Story = { name: "State=Pressed", args: { "State": "Pressed" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };
export const StateLoading: Story = { name: "State=Loading", args: { "State": "Loading" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Pressed", "Focus", "Disabled", "Loading"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Button {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const Sizes: Story = {
  name: "Sizes",
  render: (args) => (
    <div className="sb-row">
      {["xs", "sm", "base", "lg", "xl"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Size={x}</div>
          <Button {...args} {...{ "Size": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const Icons: Story = {
  name: 'Icons',
  render: (args) => (
    <div className="sb-row">
      {[["Show Leading Icon", {"Show Leading Icon": true}], ["Show Trailing Icon", {"Show Trailing Icon": true}], ["Both", {"Show Leading Icon": true, "Show Trailing Icon": true}]].map(([label, extra]: any) => (
        <div key={label}>
          <div className="sb-cell-label ts-xs-medium">{label}</div>
          <Button {...args} {...extra} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Filled", "Pill", "Outline", "Link", "Danger"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["Default", "Hover", "Pressed", "Focus", "Disabled", "Loading"].map((y) => <Button key={y} {...args} {...{ "Type": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
