// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { IconButton } from '../../components/Navigation';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Navigation/Icon Button",
  component: IconButton,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Filled",
      "Outline",
      "Ghost",
      "Danger"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Filled"
      }
    }
  },
  "Size": {
    "control": "select",
    "options": [
      "xs",
      "sm",
      "base",
      "lg",
      "xl"
    ],
    "description": "Figma variant property `Size`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "xs"
      }
    }
  },
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Pressed",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Settings"
      }
    }
  }
},
  args: {"Type": "Filled", "Size": "xs", "State": "Default", "Icon": "Icon/Settings"},
  parameters: {
    figma: { name: "Icon Button", page: "➜ Buttons & Links", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2712" },
    docs: { description: { component: "**Figma:** `Icon Button` on page `➜ Buttons & Links` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2712)\n\n**Tier:** Atom\n\n**Use:** Icon-only action in toolbars and table rows; always aria-label + Tooltip.\n\n**Figma description:**\n\n> Atom. Purpose: an action shown only as an icon (edit, delete, more, close, settings) where space is tight, e.g. table rows and toolbars.  \n> Usage rules: use only for actions whose icon is universally understood; add a Tooltip with the action name; Filled for the main action in a toolbar, Outline or Ghost for the rest, Danger for destructive actions behind a confirmation. Do not use for primary page actions (use Button with a label).  \n> Accessibility: minimum 32x32 (xs), 40x40 recommended; icon color on filled green is color/icon/inverse; needs an accessible name (aria-label) in code; Focus shows focus-ring-offset; Disabled uses opacity/disabled.  \n\n**When to use:** table row actions (Edit, Delete, More Horizontal), Close in Modal / Alert / Toast, Notifications in the Top Bar, show/hide password, Stepper, Pagination Previous/Next.\n\n**When not to use:** when the icon is not universally understood or for primary page actions (**Button** with a label).\n\n**Built from:** `Icon/*`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof IconButton>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Filled: Story = { name: "Filled", args: { "Type": "Filled" } };
export const Outline: Story = { name: "Outline", args: { "Type": "Outline" } };
export const Ghost: Story = { name: "Ghost", args: { "Type": "Ghost" } };
export const Danger: Story = { name: "Danger", args: { "Type": "Danger" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StatePressed: Story = { name: "State=Pressed", args: { "State": "Pressed" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Filled", "Outline", "Ghost", "Danger"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["Default", "Hover", "Pressed", "Focus", "Disabled"].map((y) => <IconButton key={y} {...args} {...{ "Type": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
