// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Menu, MenuInUse } from '../../components/Navigation';

const meta = {
  title: "Navigation/Menu",
  component: Menu,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {},
  args: {},
  parameters: {
    figma: { name: "Menu", page: "➜ Menus", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4370" },
    docs: { description: { component: "**Figma:** `Menu` on page `➜ Menus` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4370)\n\n**Tier:** Molecule\n\n**Use:** 2-8 actions opened from a button or row; destructive last after a divider. Picking a value -> Select / Dropdown.\n\n**Figma description:**\n\n> Molecule (Menu / Item atoms, exposed). Purpose: a short list of actions opened from a button or row (row actions in the appointments table, \"More\" menus).  \n> Usage rules: 2 to 8 items; destructive items last, after a divider, as Type=Danger; hide unused items instead of detaching; for picking a value use Select / Dropdown.  \n> Accessibility: role=\"menu\" with arrow-key navigation in code; closes on Escape and returns focus to the trigger; 40px rows.  \n\n**When to use:** row actions (opened from Icon Button `Icon/More Horizontal`), \"More\" menus, the avatar menu in the Top Bar.\n\n**When not to use:** to pick a value (**Select / Dropdown**); for navigation (**Sidebar**).\n\n**Built from:** `Menu / Item`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Menu>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};

export const InUse: Story = { name: 'In use (interactive)', render: () => <MenuInUse /> };
