// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { MenuItem } from '../../components/Navigation';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Navigation/Menu / Item",
  component: MenuItem,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Danger"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Selected",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Edit appointment"
      }
    }
  },
  "Show Leading Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Leading Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Edit"
      }
    }
  }
},
  args: {"Type": "Default", "State": "Default", "Label": "Edit appointment", "Show Leading Icon": true, "Leading Icon": "Icon/Edit"},
  parameters: {
    figma: { name: "Menu / Item", page: "➜ Menus", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3260" },
    docs: { description: { component: "**Figma:** `Menu / Item` on page `➜ Menus` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3260)\n\n**Tier:** Atom\n\n**Use:** One option in a Menu or Select / Dropdown. Danger for destructive actions, last, after a divider.\n\n**Figma description:**\n\n> Atom. Purpose: one option in a Menu or Select dropdown (row actions: Edit, Reschedule, Delete; select options: doctor names, clinics).  \n> Usage rules: used inside Menu or Select only; Selected shows a check for the current value in a Select; Danger for destructive actions, placed last and separated; labels start with a verb for actions.  \n> Accessibility: 40px high rows; Selected is shown by a check icon and semibold text, not color only; Focus shows the inset focus-ring; role=\"menuitem\"/\"option\" in code.  \n\n**When to use:** only inside **Menu** or **Select / Dropdown**.\n\n**When not to use:** alone; as a navigation link (**Sidebar / Item**).\n\n**Built from:** `Icon/*`, `Icon/Check`\n\n**Known Figma gaps (see gaps.md):** Type=Danger shows the default label and Icon/Edit; override on the instance\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof MenuItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "Type": "Default" } };
export const Danger: Story = { name: "Danger", args: { "Type": "Danger" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StateSelected: Story = { name: "State=Selected", args: { "State": "Selected" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Default", "Danger"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["Default", "Hover", "Selected", "Focus", "Disabled"].map((y) => <MenuItem key={y} {...args} {...{ "Type": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
