// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Pagination } from '../../components/Navigation';

const meta = {
  title: "Navigation/Pagination",
  component: Pagination,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "Show Summary": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Summary": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Showing 11-20 of 118 patients"
      }
    }
  }
},
  args: {"Show Summary": true, "Summary": "Showing 11-20 of 118 patients"},
  parameters: {
    figma: { name: "Pagination", page: "➜ Pagination, Tabs & Breadcrumb", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4329" },
    docs: { description: { component: "**Figma:** `Pagination` on page `➜ Pagination, Tabs & Breadcrumb` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4329)\n\n**Tier:** Molecule\n\n**Use:** Move between pages of long lists; first, last, current and neighbours with \"…\"; keep the result summary.\n\n**Figma description:**\n\n> Molecule (Pagination / Item atoms, 2 Icon Button atoms). Purpose: move between pages of long lists (patients, invoices, lab results).  \n> Usage rules: show first, last, current and neighbours with \"…\" for gaps; Previous/Next disable at the ends (swap to the Disabled Icon Button variant); keep the result summary so users know the list size; for feeds use \"Load more\" instead.  \n> Accessibility: nav element with aria-label=\"Pagination\"; current page aria-current=\"page\"; 40px targets.  \n\n**When to use:** under tables and long lists (patients, invoices, lab results).\n\n**When not to use:** feeds or short lists (\"Load more\" **Button** Outline); wizard steps.\n\n**Built from:** `Pagination / Item`, `Icon Button`, `Icon/Chevron Left`, `Icon/Chevron Right`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Pagination>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
