// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { PaginationItem } from '../../components/Navigation';

const meta = {
  title: "Navigation/Pagination / Item",
  component: PaginationItem,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Current",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Page": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "1"
      }
    }
  }
},
  args: {"State": "Default", "Page": "1"},
  parameters: {
    figma: { name: "Pagination / Item", page: "➜ Pagination, Tabs & Breadcrumb", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3176" },
    docs: { description: { component: "**Figma:** `Pagination / Item` on page `➜ Pagination, Tabs & Breadcrumb` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3176)\n\n**Tier:** Atom\n\n**Use:** One page number inside Pagination; \"…\" text in a Default item for gaps.\n\n**Figma description:**\n\n> Atom. Purpose: one page number in a Pagination bar (patient lists, invoices, lab results).  \n> Usage rules: used only inside Pagination; Current marks the page shown; use \"…\" text in a Default item for skipped ranges; previous/next are Icon Buttons (Ghost) in the Pagination molecule.  \n> Accessibility: 40x40 target; Current uses bg/brand with text/on-brand (5.6:1) and aria-current=\"page\" in code; Focus shows focus-ring-offset.  \n\n**When to use:** only inside **Pagination**.\n\n**When not to use:** alone.\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof PaginationItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Current: Story = { name: "Current", args: { "State": "Current" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Current", "Focus", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <PaginationItem {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
