// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Sidebar } from '../../components/Navigation';

const meta = {
  title: "Navigation/Sidebar",
  component: Sidebar,
  tags: ['autodocs', 'tier-organism'],
  argTypes: {},
  args: {},
  parameters: {
    figma: { name: "Sidebar", page: "➜ Navigation Bars", tier: "Organism", order: 3 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4454" },
    docs: { description: { component: "**Figma:** `Sidebar` on page `➜ Navigation Bars` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4454)\n\n**Tier:** Organism\n\n**Use:** Main app navigation on Desktop and iPad, 264px wide; up to 8 items, Settings and Log Out pinned at the bottom.\n\n**Figma description:**\n\n> Organism (Sidebar / Item molecules, exposed). Purpose: main navigation of the ClinicSoft web app on desktop and iPad.  \n> Usage rules: 264px wide, full screen height, left side; one Sidebar / Item Selected for the current section; up to 8 main items, Settings and Log Out pinned at the bottom; collapse to a menu Icon Button in the Top Bar on mobile. Set each item through its exposed properties.  \n> Accessibility: nav landmark with aria-label=\"Main\"; current item aria-current=\"page\"; keyboard order top to bottom.  \n\n**When to use:** every app page on Desktop and iPad, left of the **Top Bar**.\n\n**When not to use:** on mobile (collapse into the Top Bar menu Icon Button); for in-page sections (**Tabs / Bar**).\n\n**Built from:** `Sidebar / Item`, `Badge`, `Icon/Heart Pulse`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Sidebar>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
