// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { SidebarItem } from '../../components/Navigation';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Navigation/Sidebar / Item",
  component: SidebarItem,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Selected",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Appointments"
      }
    }
  },
  "Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Calendar"
      }
    }
  },
  "Show Count": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Appointments", "Icon": "Icon/Calendar", "Show Count": false},
  parameters: {
    figma: { name: "Sidebar / Item", page: "➜ Navigation Bars", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4450" },
    docs: { description: { component: "**Figma:** `Sidebar / Item` on page `➜ Navigation Bars` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4450)\n\n**Tier:** Molecule\n\n**Use:** One Sidebar destination; exactly one Selected.\n\n**Figma description:**\n\n> Molecule (Icon, label and Badge atom). Purpose: one destination in the Sidebar (Dashboard, Appointments, Patients, Billing, Settings).  \n> Usage rules: used inside Sidebar only; exactly one Selected (the current section); Show Count for pending items (e.g. new lab results); labels are nouns.  \n> Accessibility: 40px rows; Selected = bg/subtle + semibold + brand icon, not color only; aria-current=\"page\" in code; Focus shows the inset focus-ring.  \n\n**When to use:** only inside **Sidebar**.\n\n**When not to use:** for actions (**Button**, **Menu / Item**); inside page content.\n\n**Built from:** `Icon/*`, `Badge`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof SidebarItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Selected: Story = { name: "Selected", args: { "State": "Selected" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Selected", "Focus", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <SidebarItem {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
