// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { TabsBar } from '../../components/Navigation';

const meta = {
  title: "Navigation/Tabs / Bar",
  component: TabsBar,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Underline",
      "Segmented"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Underline"
      }
    }
  }
},
  args: {"Type": "Underline"},
  parameters: {
    figma: { name: "Tabs / Bar", page: "➜ Pagination, Tabs & Breadcrumb", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4325" },
    docs: { description: { component: "**Figma:** `Tabs / Bar` on page `➜ Pagination, Tabs & Breadcrumb` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4325)\n\n**Tier:** Molecule\n\n**Use:** Underline for sections of one page; Segmented for view switchers (Day / Week / Month). 2 to 7 tabs, exactly one Selected.\n\n**Figma description:**\n\n> Molecule (4 Tabs / Item atoms, exposed). Purpose: switch between sections of one page (patient Overview / Visits / Prescriptions / Files) or between views (Day / Week / Month).  \n> Usage rules: Underline for page sections, Segmented for compact view switches; exactly one tab Selected; 2 to 7 tabs, hide extra Tab instances rather than detaching; set each tab through its exposed properties.  \n> Accessibility: role=\"tablist\" with arrow-key navigation in code; the selected tab is marked by weight + underline/fill, not color only.  \n\n**When to use:** Underline under a page title for sections of one record; Segmented for calendar Day / Week / Month or List / Grid.\n\n**When not to use:** more than 7 tabs or long labels (**Select / Dropdown** or **Sidebar**); actions.\n\n**Built from:** `Tabs / Item`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof TabsBar>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Underline: Story = { name: "Underline", args: { "Type": "Underline" } };
export const Segmented: Story = { name: "Segmented", args: { "Type": "Segmented" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Underline", "Segmented"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <TabsBar {...args} {...{ "Type": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <TabsBar Type="Underline" showPanel /> };
