// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { TabsItem } from '../../components/Navigation';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Navigation/Tabs / Item",
  component: TabsItem,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Type": {
    "control": "inline-radio",
    "options": [
      "Underline",
      "Segmented"
    ],
    "description": "Figma variant property `Type`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Underline"
      }
    }
  },
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Selected",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Appointments"
      }
    }
  },
  "Show Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Calendar"
      }
    }
  }
},
  args: {"Type": "Underline", "State": "Default", "Label": "Appointments", "Show Icon": false, "Icon": "Icon/Calendar"},
  parameters: {
    figma: { name: "Tabs / Item", page: "➜ Pagination, Tabs & Breadcrumb", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3162" },
    docs: { description: { component: "**Figma:** `Tabs / Item` on page `➜ Pagination, Tabs & Breadcrumb` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=6-3162)\n\n**Tier:** Atom\n\n**Use:** One tab; only inside Tabs / Bar.\n\n**Figma description:**\n\n> Atom. Purpose: one tab that switches between views of the same page (Patient: Overview / Visits / Prescriptions / Files).  \n> Usage rules: use inside Tabs / Bar only; Underline for page-level sections, Segmented for compact view switches (Day / Week / Month); exactly one Selected per bar; 2 to 7 tabs; labels are one or two words. To move to another page use navigation (Sidebar, Breadcrumb), not tabs.  \n> Accessibility: 40px high; selected tab has a 2px color/border/brand underline plus semibold text, so the state is not color only; role=\"tab\" with arrow key navigation in code; Focus shows focus-ring-offset.  \n\n**When to use:** only inside **Tabs / Bar**.\n\n**When not to use:** alone; to trigger actions (**Button**); to move to another page (**Sidebar**, **Breadcrumb**).\n\n**Built from:** `Icon/*`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof TabsItem>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Underline: Story = { name: "Underline", args: { "Type": "Underline" } };
export const Segmented: Story = { name: "Segmented", args: { "Type": "Segmented" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StateSelected: Story = { name: "State=Selected", args: { "State": "Selected" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Selected", "Focus", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <TabsItem {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Underline", "Segmented"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Type={x}</div>
          <div className="sb-row">{["Default", "Hover", "Selected", "Focus", "Disabled"].map((y) => <TabsItem key={y} {...args} {...{ "Type": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
