// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { TopBar } from '../../components/Navigation';

const meta = {
  title: "Navigation/Top Bar",
  component: TopBar,
  tags: ['!autodocs', 'tier-organism'],
  argTypes: {
  "Page Title": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Appointments"
      }
    }
  },
  "Show Primary Action": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Show Search": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Page Title": "Appointments", "Show Primary Action": true, "Show Search": true},
  parameters: {
    figma: { name: "Top Bar", page: "➜ Navigation Bars", tier: "Organism", order: 3 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4569" },
    docs: { description: { component: "**Figma:** `Top Bar` on page `➜ Navigation Bars` (Navigation). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=8-4569)\n\n**Tier:** Organism\n\n**Use:** Page header next to the Sidebar: title, search, notifications, one primary action, user. 64px high, 1176px on desktop.\n\n**Figma description:**\n\n> Organism (Search molecule, Icon Button, Button and Avatar atoms). Purpose: the header of every app page next to the Sidebar: page title, search, notifications, the page's main action and the signed-in user.  \n> Usage rules: 64px high, fills the content width (1440 - 264 sidebar = 1176 on desktop); one Primary Action at most (it is the page's Filled button); hide Search on pages without searchable content; on mobile the title shrinks and a menu Icon Button opens the Sidebar.  \n> Accessibility: header landmark; Notifications Icon Button needs aria-label and an unread count in text; tab order: title, search, notifications, action, avatar menu.  \n\n**When to use:** top of every app page, right of the **Sidebar**.\n\n**When not to use:** inside Modals or cards; with more than one Filled action.\n\n**Built from:** `Search`, `Icon Button`, `Button`, `Avatar`, `Icon/Bell`, `Icon/Add`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof TopBar>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
