// Generated by tools/tokens_to_css.py from data/tokens.json. Do not edit by hand.
export const tokens = {
 "platform": "web",
 "platform_label": "CSS variable",
 "platform_file": "tokens.css",
 "meta": {
  "platform": "Web",
  "figma_file": "NEW PROJECT Design system (to be renamed ClinicSoft Design System)",
  "figma_url": "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU",
  "source": {
   "method": "figma-console figma_export_tokens (Desktop Bridge, read-only)",
   "file": "My Projects/ClinicSoft/data/source/figma-variables.dtcg.json",
   "needs_resync": false
  },
  "generated_at": "2026-09-30",
  "generated_by": "tools/build_tokens.py",
  "naming": "Keys are \"<Collection>::<variable name>\" exactly as in Figma. Find variables by this name, never by id.",
  "recolor": "See rules.json > recolor and tools/recolor.py"
 },
 "collections": {
  "Primitives": {
   "modes": [
    "Value"
   ],
   "default": "Value",
   "attribute": "data-primitives",
   "role": "primitive"
  },
  "Semantic": {
   "modes": [
    "Dark"
   ],
   "default": "Dark",
   "attribute": "data-semantic",
   "role": "semantic"
  },
  "Spacing": {
   "modes": [
    "Desktop",
    "iPad",
    "Mobile"
   ],
   "default": "Desktop",
   "attribute": "data-spacing",
   "role": "spacing"
  },
  "Radius": {
   "modes": [
    "Value"
   ],
   "default": "Value",
   "attribute": "data-radius",
   "role": "radius"
  },
  "Opacity": {
   "modes": [
    "Value"
   ],
   "default": "Value",
   "attribute": "data-opacity",
   "role": "opacity"
  },
  "Typography": {
   "modes": [
    "Desktop",
    "iPad",
    "Mobile"
   ],
   "default": "Desktop",
   "attribute": "data-typography",
   "role": "typography"
  }
 },
 "tokens": [
  {
   "figma": "Primitives::gray/50",
   "collection": "Primitives",
   "name": "gray/50",
   "type": "color",
   "css": "--gray-50",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-50"
    }
   ],
   "values": {
    "Value": "#F8FAFC"
   },
   "resolved": {
    "Value": "#F8FAFC"
   },
   "description": "#F8FAFC. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/100",
   "collection": "Primitives",
   "name": "gray/100",
   "type": "color",
   "css": "--gray-100",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-100"
    }
   ],
   "values": {
    "Value": "#F1F5F9"
   },
   "resolved": {
    "Value": "#F1F5F9"
   },
   "description": "#F1F5F9. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/200",
   "collection": "Primitives",
   "name": "gray/200",
   "type": "color",
   "css": "--gray-200",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-200"
    }
   ],
   "values": {
    "Value": "#E2E8F0"
   },
   "resolved": {
    "Value": "#E2E8F0"
   },
   "description": "#E2E8F0. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/300",
   "collection": "Primitives",
   "name": "gray/300",
   "type": "color",
   "css": "--gray-300",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-300"
    }
   ],
   "values": {
    "Value": "#CBD5E1"
   },
   "resolved": {
    "Value": "#CBD5E1"
   },
   "description": "#CBD5E1. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/400",
   "collection": "Primitives",
   "name": "gray/400",
   "type": "color",
   "css": "--gray-400",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-400"
    }
   ],
   "values": {
    "Value": "#94A3B8"
   },
   "resolved": {
    "Value": "#94A3B8"
   },
   "description": "#94A3B8. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/500",
   "collection": "Primitives",
   "name": "gray/500",
   "type": "color",
   "css": "--gray-500",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-500"
    }
   ],
   "values": {
    "Value": "#64748B"
   },
   "resolved": {
    "Value": "#64748B"
   },
   "description": "#64748B. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/600",
   "collection": "Primitives",
   "name": "gray/600",
   "type": "color",
   "css": "--gray-600",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-600"
    }
   ],
   "values": {
    "Value": "#475569"
   },
   "resolved": {
    "Value": "#475569"
   },
   "description": "#475569. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/700",
   "collection": "Primitives",
   "name": "gray/700",
   "type": "color",
   "css": "--gray-700",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-700"
    }
   ],
   "values": {
    "Value": "#334155"
   },
   "resolved": {
    "Value": "#334155"
   },
   "description": "#334155. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/800",
   "collection": "Primitives",
   "name": "gray/800",
   "type": "color",
   "css": "--gray-800",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-800"
    }
   ],
   "values": {
    "Value": "#1E293B"
   },
   "resolved": {
    "Value": "#1E293B"
   },
   "description": "#1E293B. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/900",
   "collection": "Primitives",
   "name": "gray/900",
   "type": "color",
   "css": "--gray-900",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-900"
    }
   ],
   "values": {
    "Value": "#0F172A"
   },
   "resolved": {
    "Value": "#0F172A"
   },
   "description": "#0F172A. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::gray/950",
   "collection": "Primitives",
   "name": "gray/950",
   "type": "color",
   "css": "--gray-950",
   "code": [
    {
     "label": "CSS variable",
     "name": "--gray-950"
    }
   ],
   "values": {
    "Value": "#020617"
   },
   "resolved": {
    "Value": "#020617"
   },
   "description": "#020617. Cool neutral scale (Tailwind slate). Surfaces, text and borders in Dark."
  },
  {
   "figma": "Primitives::brand/50",
   "collection": "Primitives",
   "name": "brand/50",
   "type": "color",
   "css": "--brand-50",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-50"
    }
   ],
   "values": {
    "Value": "#F2FCF3"
   },
   "resolved": {
    "Value": "#F2FCF3"
   },
   "description": "#F2FCF3. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/100",
   "collection": "Primitives",
   "name": "brand/100",
   "type": "color",
   "css": "--brand-100",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-100"
    }
   ],
   "values": {
    "Value": "#DDFAE6"
   },
   "resolved": {
    "Value": "#DDFAE6"
   },
   "description": "#DDFAE6. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/200",
   "collection": "Primitives",
   "name": "brand/200",
   "type": "color",
   "css": "--brand-200",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-200"
    }
   ],
   "values": {
    "Value": "#BDF4CF"
   },
   "resolved": {
    "Value": "#BDF4CF"
   },
   "description": "#BDF4CF. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/300",
   "collection": "Primitives",
   "name": "brand/300",
   "type": "color",
   "css": "--brand-300",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-300"
    }
   ],
   "values": {
    "Value": "#8DEAAB"
   },
   "resolved": {
    "Value": "#8DEAAB"
   },
   "description": "#8DEAAB. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/400",
   "collection": "Primitives",
   "name": "brand/400",
   "type": "color",
   "css": "--brand-400",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-400"
    }
   ],
   "values": {
    "Value": "#59D77F"
   },
   "resolved": {
    "Value": "#59D77F"
   },
   "description": "#59D77F. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/500",
   "collection": "Primitives",
   "name": "brand/500",
   "type": "color",
   "css": "--brand-500",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-500"
    }
   ],
   "values": {
    "Value": "#39BD5D"
   },
   "resolved": {
    "Value": "#39BD5D"
   },
   "description": "#39BD5D. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/600",
   "collection": "Primitives",
   "name": "brand/600",
   "type": "color",
   "css": "--brand-600",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-600"
    }
   ],
   "values": {
    "Value": "#299B48"
   },
   "resolved": {
    "Value": "#299B48"
   },
   "description": "#299B48. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/700",
   "collection": "Primitives",
   "name": "brand/700",
   "type": "color",
   "css": "--brand-700",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-700"
    }
   ],
   "values": {
    "Value": "#227A3C"
   },
   "resolved": {
    "Value": "#227A3C"
   },
   "description": "#227A3C. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/800",
   "collection": "Primitives",
   "name": "brand/800",
   "type": "color",
   "css": "--brand-800",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-800"
    }
   ],
   "values": {
    "Value": "#1E6133"
   },
   "resolved": {
    "Value": "#1E6133"
   },
   "description": "#1E6133. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/900",
   "collection": "Primitives",
   "name": "brand/900",
   "type": "color",
   "css": "--brand-900",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-900"
    }
   ],
   "values": {
    "Value": "#1B512D"
   },
   "resolved": {
    "Value": "#1B512D"
   },
   "description": "#1B512D. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::brand/950",
   "collection": "Primitives",
   "name": "brand/950",
   "type": "color",
   "css": "--brand-950",
   "code": [
    {
     "label": "CSS variable",
     "name": "--brand-950"
    }
   ],
   "values": {
    "Value": "#0A2D17"
   },
   "resolved": {
    "Value": "#0A2D17"
   },
   "description": "#0A2D17. ClinicSoft brand green. Base #299B48 at step 600, OKLCH curve from Tailwind green. Recolor with tools/recolor.py."
  },
  {
   "figma": "Primitives::green/50",
   "collection": "Primitives",
   "name": "green/50",
   "type": "color",
   "css": "--green-50",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-50"
    }
   ],
   "values": {
    "Value": "#ECFDF5"
   },
   "resolved": {
    "Value": "#ECFDF5"
   },
   "description": "#ECFDF5. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/100",
   "collection": "Primitives",
   "name": "green/100",
   "type": "color",
   "css": "--green-100",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-100"
    }
   ],
   "values": {
    "Value": "#D1FAE5"
   },
   "resolved": {
    "Value": "#D1FAE5"
   },
   "description": "#D1FAE5. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/200",
   "collection": "Primitives",
   "name": "green/200",
   "type": "color",
   "css": "--green-200",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-200"
    }
   ],
   "values": {
    "Value": "#A7F3D0"
   },
   "resolved": {
    "Value": "#A7F3D0"
   },
   "description": "#A7F3D0. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/300",
   "collection": "Primitives",
   "name": "green/300",
   "type": "color",
   "css": "--green-300",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-300"
    }
   ],
   "values": {
    "Value": "#6EE7B7"
   },
   "resolved": {
    "Value": "#6EE7B7"
   },
   "description": "#6EE7B7. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/400",
   "collection": "Primitives",
   "name": "green/400",
   "type": "color",
   "css": "--green-400",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-400"
    }
   ],
   "values": {
    "Value": "#34D399"
   },
   "resolved": {
    "Value": "#34D399"
   },
   "description": "#34D399. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/500",
   "collection": "Primitives",
   "name": "green/500",
   "type": "color",
   "css": "--green-500",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-500"
    }
   ],
   "values": {
    "Value": "#10B981"
   },
   "resolved": {
    "Value": "#10B981"
   },
   "description": "#10B981. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/600",
   "collection": "Primitives",
   "name": "green/600",
   "type": "color",
   "css": "--green-600",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-600"
    }
   ],
   "values": {
    "Value": "#059669"
   },
   "resolved": {
    "Value": "#059669"
   },
   "description": "#059669. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/700",
   "collection": "Primitives",
   "name": "green/700",
   "type": "color",
   "css": "--green-700",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-700"
    }
   ],
   "values": {
    "Value": "#047857"
   },
   "resolved": {
    "Value": "#047857"
   },
   "description": "#047857. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/800",
   "collection": "Primitives",
   "name": "green/800",
   "type": "color",
   "css": "--green-800",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-800"
    }
   ],
   "values": {
    "Value": "#065F46"
   },
   "resolved": {
    "Value": "#065F46"
   },
   "description": "#065F46. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/900",
   "collection": "Primitives",
   "name": "green/900",
   "type": "color",
   "css": "--green-900",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-900"
    }
   ],
   "values": {
    "Value": "#064E3B"
   },
   "resolved": {
    "Value": "#064E3B"
   },
   "description": "#064E3B. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::green/950",
   "collection": "Primitives",
   "name": "green/950",
   "type": "color",
   "css": "--green-950",
   "code": [
    {
     "label": "CSS variable",
     "name": "--green-950"
    }
   ],
   "values": {
    "Value": "#022C22"
   },
   "resolved": {
    "Value": "#022C22"
   },
   "description": "#022C22. Success scale (Tailwind emerald), kept apart from brand so success never reads as an action."
  },
  {
   "figma": "Primitives::red/50",
   "collection": "Primitives",
   "name": "red/50",
   "type": "color",
   "css": "--red-50",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-50"
    }
   ],
   "values": {
    "Value": "#FEF2F2"
   },
   "resolved": {
    "Value": "#FEF2F2"
   },
   "description": "#FEF2F2. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/100",
   "collection": "Primitives",
   "name": "red/100",
   "type": "color",
   "css": "--red-100",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-100"
    }
   ],
   "values": {
    "Value": "#FEE2E2"
   },
   "resolved": {
    "Value": "#FEE2E2"
   },
   "description": "#FEE2E2. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/200",
   "collection": "Primitives",
   "name": "red/200",
   "type": "color",
   "css": "--red-200",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-200"
    }
   ],
   "values": {
    "Value": "#FECACA"
   },
   "resolved": {
    "Value": "#FECACA"
   },
   "description": "#FECACA. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/300",
   "collection": "Primitives",
   "name": "red/300",
   "type": "color",
   "css": "--red-300",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-300"
    }
   ],
   "values": {
    "Value": "#FCA5A5"
   },
   "resolved": {
    "Value": "#FCA5A5"
   },
   "description": "#FCA5A5. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/400",
   "collection": "Primitives",
   "name": "red/400",
   "type": "color",
   "css": "--red-400",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-400"
    }
   ],
   "values": {
    "Value": "#F87171"
   },
   "resolved": {
    "Value": "#F87171"
   },
   "description": "#F87171. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/500",
   "collection": "Primitives",
   "name": "red/500",
   "type": "color",
   "css": "--red-500",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-500"
    }
   ],
   "values": {
    "Value": "#EF4444"
   },
   "resolved": {
    "Value": "#EF4444"
   },
   "description": "#EF4444. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/600",
   "collection": "Primitives",
   "name": "red/600",
   "type": "color",
   "css": "--red-600",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-600"
    }
   ],
   "values": {
    "Value": "#DC2626"
   },
   "resolved": {
    "Value": "#DC2626"
   },
   "description": "#DC2626. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/700",
   "collection": "Primitives",
   "name": "red/700",
   "type": "color",
   "css": "--red-700",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-700"
    }
   ],
   "values": {
    "Value": "#B91C1C"
   },
   "resolved": {
    "Value": "#B91C1C"
   },
   "description": "#B91C1C. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/800",
   "collection": "Primitives",
   "name": "red/800",
   "type": "color",
   "css": "--red-800",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-800"
    }
   ],
   "values": {
    "Value": "#991B1B"
   },
   "resolved": {
    "Value": "#991B1B"
   },
   "description": "#991B1B. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/900",
   "collection": "Primitives",
   "name": "red/900",
   "type": "color",
   "css": "--red-900",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-900"
    }
   ],
   "values": {
    "Value": "#7F1D1D"
   },
   "resolved": {
    "Value": "#7F1D1D"
   },
   "description": "#7F1D1D. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::red/950",
   "collection": "Primitives",
   "name": "red/950",
   "type": "color",
   "css": "--red-950",
   "code": [
    {
     "label": "CSS variable",
     "name": "--red-950"
    }
   ],
   "values": {
    "Value": "#450A0A"
   },
   "resolved": {
    "Value": "#450A0A"
   },
   "description": "#450A0A. Error and danger scale (Tailwind red)."
  },
  {
   "figma": "Primitives::yellow/50",
   "collection": "Primitives",
   "name": "yellow/50",
   "type": "color",
   "css": "--yellow-50",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-50"
    }
   ],
   "values": {
    "Value": "#FFFBEB"
   },
   "resolved": {
    "Value": "#FFFBEB"
   },
   "description": "#FFFBEB. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/100",
   "collection": "Primitives",
   "name": "yellow/100",
   "type": "color",
   "css": "--yellow-100",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-100"
    }
   ],
   "values": {
    "Value": "#FEF3C7"
   },
   "resolved": {
    "Value": "#FEF3C7"
   },
   "description": "#FEF3C7. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/200",
   "collection": "Primitives",
   "name": "yellow/200",
   "type": "color",
   "css": "--yellow-200",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-200"
    }
   ],
   "values": {
    "Value": "#FDE68A"
   },
   "resolved": {
    "Value": "#FDE68A"
   },
   "description": "#FDE68A. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/300",
   "collection": "Primitives",
   "name": "yellow/300",
   "type": "color",
   "css": "--yellow-300",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-300"
    }
   ],
   "values": {
    "Value": "#FCD34D"
   },
   "resolved": {
    "Value": "#FCD34D"
   },
   "description": "#FCD34D. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/400",
   "collection": "Primitives",
   "name": "yellow/400",
   "type": "color",
   "css": "--yellow-400",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-400"
    }
   ],
   "values": {
    "Value": "#FBBF24"
   },
   "resolved": {
    "Value": "#FBBF24"
   },
   "description": "#FBBF24. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/500",
   "collection": "Primitives",
   "name": "yellow/500",
   "type": "color",
   "css": "--yellow-500",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-500"
    }
   ],
   "values": {
    "Value": "#F59E0B"
   },
   "resolved": {
    "Value": "#F59E0B"
   },
   "description": "#F59E0B. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/600",
   "collection": "Primitives",
   "name": "yellow/600",
   "type": "color",
   "css": "--yellow-600",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-600"
    }
   ],
   "values": {
    "Value": "#D97706"
   },
   "resolved": {
    "Value": "#D97706"
   },
   "description": "#D97706. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/700",
   "collection": "Primitives",
   "name": "yellow/700",
   "type": "color",
   "css": "--yellow-700",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-700"
    }
   ],
   "values": {
    "Value": "#B45309"
   },
   "resolved": {
    "Value": "#B45309"
   },
   "description": "#B45309. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/800",
   "collection": "Primitives",
   "name": "yellow/800",
   "type": "color",
   "css": "--yellow-800",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-800"
    }
   ],
   "values": {
    "Value": "#92400E"
   },
   "resolved": {
    "Value": "#92400E"
   },
   "description": "#92400E. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/900",
   "collection": "Primitives",
   "name": "yellow/900",
   "type": "color",
   "css": "--yellow-900",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-900"
    }
   ],
   "values": {
    "Value": "#78350F"
   },
   "resolved": {
    "Value": "#78350F"
   },
   "description": "#78350F. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::yellow/950",
   "collection": "Primitives",
   "name": "yellow/950",
   "type": "color",
   "css": "--yellow-950",
   "code": [
    {
     "label": "CSS variable",
     "name": "--yellow-950"
    }
   ],
   "values": {
    "Value": "#451A03"
   },
   "resolved": {
    "Value": "#451A03"
   },
   "description": "#451A03. Warning scale (Tailwind amber)."
  },
  {
   "figma": "Primitives::blue/50",
   "collection": "Primitives",
   "name": "blue/50",
   "type": "color",
   "css": "--blue-50",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-50"
    }
   ],
   "values": {
    "Value": "#EFF6FF"
   },
   "resolved": {
    "Value": "#EFF6FF"
   },
   "description": "#EFF6FF. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/100",
   "collection": "Primitives",
   "name": "blue/100",
   "type": "color",
   "css": "--blue-100",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-100"
    }
   ],
   "values": {
    "Value": "#DBEAFE"
   },
   "resolved": {
    "Value": "#DBEAFE"
   },
   "description": "#DBEAFE. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/200",
   "collection": "Primitives",
   "name": "blue/200",
   "type": "color",
   "css": "--blue-200",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-200"
    }
   ],
   "values": {
    "Value": "#BFDBFE"
   },
   "resolved": {
    "Value": "#BFDBFE"
   },
   "description": "#BFDBFE. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/300",
   "collection": "Primitives",
   "name": "blue/300",
   "type": "color",
   "css": "--blue-300",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-300"
    }
   ],
   "values": {
    "Value": "#93C5FD"
   },
   "resolved": {
    "Value": "#93C5FD"
   },
   "description": "#93C5FD. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/400",
   "collection": "Primitives",
   "name": "blue/400",
   "type": "color",
   "css": "--blue-400",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-400"
    }
   ],
   "values": {
    "Value": "#60A5FA"
   },
   "resolved": {
    "Value": "#60A5FA"
   },
   "description": "#60A5FA. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/500",
   "collection": "Primitives",
   "name": "blue/500",
   "type": "color",
   "css": "--blue-500",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-500"
    }
   ],
   "values": {
    "Value": "#3B82F6"
   },
   "resolved": {
    "Value": "#3B82F6"
   },
   "description": "#3B82F6. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/600",
   "collection": "Primitives",
   "name": "blue/600",
   "type": "color",
   "css": "--blue-600",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-600"
    }
   ],
   "values": {
    "Value": "#2563EB"
   },
   "resolved": {
    "Value": "#2563EB"
   },
   "description": "#2563EB. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/700",
   "collection": "Primitives",
   "name": "blue/700",
   "type": "color",
   "css": "--blue-700",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-700"
    }
   ],
   "values": {
    "Value": "#1D4ED8"
   },
   "resolved": {
    "Value": "#1D4ED8"
   },
   "description": "#1D4ED8. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/800",
   "collection": "Primitives",
   "name": "blue/800",
   "type": "color",
   "css": "--blue-800",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-800"
    }
   ],
   "values": {
    "Value": "#1E40AF"
   },
   "resolved": {
    "Value": "#1E40AF"
   },
   "description": "#1E40AF. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/900",
   "collection": "Primitives",
   "name": "blue/900",
   "type": "color",
   "css": "--blue-900",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-900"
    }
   ],
   "values": {
    "Value": "#1E3A8A"
   },
   "resolved": {
    "Value": "#1E3A8A"
   },
   "description": "#1E3A8A. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::blue/950",
   "collection": "Primitives",
   "name": "blue/950",
   "type": "color",
   "css": "--blue-950",
   "code": [
    {
     "label": "CSS variable",
     "name": "--blue-950"
    }
   ],
   "values": {
    "Value": "#172554"
   },
   "resolved": {
    "Value": "#172554"
   },
   "description": "#172554. Info scale (Tailwind blue)."
  },
  {
   "figma": "Primitives::white",
   "collection": "Primitives",
   "name": "white",
   "type": "color",
   "css": "--white",
   "code": [
    {
     "label": "CSS variable",
     "name": "--white"
    }
   ],
   "values": {
    "Value": "#FFFFFF"
   },
   "resolved": {
    "Value": "#FFFFFF"
   },
   "description": "#FFFFFF. Pure white."
  },
  {
   "figma": "Primitives::black",
   "collection": "Primitives",
   "name": "black",
   "type": "color",
   "css": "--black",
   "code": [
    {
     "label": "CSS variable",
     "name": "--black"
    }
   ],
   "values": {
    "Value": "#000000"
   },
   "resolved": {
    "Value": "#000000"
   },
   "description": "#000000. Pure black."
  },
  {
   "figma": "Primitives::alpha/black-50",
   "collection": "Primitives",
   "name": "alpha/black-50",
   "type": "color",
   "css": "--alpha-black-50",
   "code": [
    {
     "label": "CSS variable",
     "name": "--alpha-black-50"
    }
   ],
   "values": {
    "Value": "#00000080"
   },
   "resolved": {
    "Value": "#00000080"
   },
   "description": "#000000 at 50% opacity. Scrims and overlays."
  },
  {
   "figma": "Primitives::alpha/black-70",
   "collection": "Primitives",
   "name": "alpha/black-70",
   "type": "color",
   "css": "--alpha-black-70",
   "code": [
    {
     "label": "CSS variable",
     "name": "--alpha-black-70"
    }
   ],
   "values": {
    "Value": "#000000B2"
   },
   "resolved": {
    "Value": "#000000B2"
   },
   "description": "#000000 at 70% opacity. Scrims and overlays."
  },
  {
   "figma": "Primitives::alpha/white-10",
   "collection": "Primitives",
   "name": "alpha/white-10",
   "type": "color",
   "css": "--alpha-white-10",
   "code": [
    {
     "label": "CSS variable",
     "name": "--alpha-white-10"
    }
   ],
   "values": {
    "Value": "#FFFFFF1A"
   },
   "resolved": {
    "Value": "#FFFFFF1A"
   },
   "description": "#FFFFFF at 10% opacity. Scrims and overlays."
  },
  {
   "figma": "Semantic::color/text/primary",
   "collection": "Semantic",
   "name": "color/text/primary",
   "type": "color",
   "css": "--color-text-primary",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-primary"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    }
   },
   "resolved": {
    "Dark": "#F8FAFC"
   },
   "description": "Main body and heading text. Dark: gray/50."
  },
  {
   "figma": "Semantic::color/text/secondary",
   "collection": "Semantic",
   "name": "color/text/secondary",
   "type": "color",
   "css": "--color-text-secondary",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-secondary"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/300"
    }
   },
   "resolved": {
    "Dark": "#CBD5E1"
   },
   "description": "Supporting text, labels. Dark: gray/300."
  },
  {
   "figma": "Semantic::color/text/muted",
   "collection": "Semantic",
   "name": "color/text/muted",
   "type": "color",
   "css": "--color-text-muted",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-muted"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/400"
    }
   },
   "resolved": {
    "Dark": "#94A3B8"
   },
   "description": "Hints, captions, timestamps (7.9:1 on bg/primary). Dark: gray/400."
  },
  {
   "figma": "Semantic::color/text/placeholder",
   "collection": "Semantic",
   "name": "color/text/placeholder",
   "type": "color",
   "css": "--color-text-placeholder",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-placeholder"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/400"
    }
   },
   "resolved": {
    "Dark": "#94A3B8"
   },
   "description": "Input placeholder text. Dark: gray/400."
  },
  {
   "figma": "Semantic::color/text/disabled",
   "collection": "Semantic",
   "name": "color/text/disabled",
   "type": "color",
   "css": "--color-text-disabled",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-disabled"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/500"
    }
   },
   "resolved": {
    "Dark": "#64748B"
   },
   "description": "Text in disabled controls (shown at opacity/disabled). Dark: gray/500."
  },
  {
   "figma": "Semantic::color/text/inverse",
   "collection": "Semantic",
   "name": "color/text/inverse",
   "type": "color",
   "css": "--color-text-inverse",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-inverse"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/950"
    }
   },
   "resolved": {
    "Dark": "#020617"
   },
   "description": "Text on bg/inverse. Dark: gray/950."
  },
  {
   "figma": "Semantic::color/text/link",
   "collection": "Semantic",
   "name": "color/text/link",
   "type": "color",
   "css": "--color-text-link",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-link"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/400"
    }
   },
   "resolved": {
    "Dark": "#59D77F"
   },
   "description": "Inline links. Dark: brand/400."
  },
  {
   "figma": "Semantic::color/text/link-hover",
   "collection": "Semantic",
   "name": "color/text/link-hover",
   "type": "color",
   "css": "--color-text-link-hover",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-link-hover"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/300"
    }
   },
   "resolved": {
    "Dark": "#8DEAAB"
   },
   "description": "Link hover. Dark: brand/300."
  },
  {
   "figma": "Semantic::color/text/error",
   "collection": "Semantic",
   "name": "color/text/error",
   "type": "color",
   "css": "--color-text-error",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-error"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/400"
    }
   },
   "resolved": {
    "Dark": "#F87171"
   },
   "description": "Error messages. Dark: red/400."
  },
  {
   "figma": "Semantic::color/text/warning",
   "collection": "Semantic",
   "name": "color/text/warning",
   "type": "color",
   "css": "--color-text-warning",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-warning"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/400"
    }
   },
   "resolved": {
    "Dark": "#FBBF24"
   },
   "description": "Warning messages. Dark: yellow/400."
  },
  {
   "figma": "Semantic::color/text/success",
   "collection": "Semantic",
   "name": "color/text/success",
   "type": "color",
   "css": "--color-text-success",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-success"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::green/400"
    }
   },
   "resolved": {
    "Dark": "#34D399"
   },
   "description": "Success messages. Dark: green/400."
  },
  {
   "figma": "Semantic::color/text/info",
   "collection": "Semantic",
   "name": "color/text/info",
   "type": "color",
   "css": "--color-text-info",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-info"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    }
   },
   "resolved": {
    "Dark": "#60A5FA"
   },
   "description": "Info messages. Dark: blue/400."
  },
  {
   "figma": "Semantic::color/text/on-brand",
   "collection": "Semantic",
   "name": "color/text/on-brand",
   "type": "color",
   "css": "--color-text-on-brand",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-text-on-brand"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/950"
    }
   },
   "resolved": {
    "Dark": "#020617"
   },
   "description": "Text and icons on bg/brand (white fails at 3.6:1). Dark: gray/950."
  },
  {
   "figma": "Semantic::color/bg/primary",
   "collection": "Semantic",
   "name": "color/bg/primary",
   "type": "color",
   "css": "--color-bg-primary",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-primary"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/950"
    }
   },
   "resolved": {
    "Dark": "#020617"
   },
   "description": "Page background. Dark: gray/950."
  },
  {
   "figma": "Semantic::color/bg/secondary",
   "collection": "Semantic",
   "name": "color/bg/secondary",
   "type": "color",
   "css": "--color-bg-secondary",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-secondary"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/900"
    }
   },
   "resolved": {
    "Dark": "#0F172A"
   },
   "description": "Cards, panels, inputs. Dark: gray/900."
  },
  {
   "figma": "Semantic::color/bg/subtle",
   "collection": "Semantic",
   "name": "color/bg/subtle",
   "type": "color",
   "css": "--color-bg-subtle",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-subtle"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    }
   },
   "resolved": {
    "Dark": "#1E293B"
   },
   "description": "Raised rows, hover backgrounds. Dark: gray/800."
  },
  {
   "figma": "Semantic::color/bg/muted",
   "collection": "Semantic",
   "name": "color/bg/muted",
   "type": "color",
   "css": "--color-bg-muted",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-muted"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/700"
    }
   },
   "resolved": {
    "Dark": "#334155"
   },
   "description": "Tracks, dividers as fills, disabled fills. Dark: gray/700."
  },
  {
   "figma": "Semantic::color/bg/inverse",
   "collection": "Semantic",
   "name": "color/bg/inverse",
   "type": "color",
   "css": "--color-bg-inverse",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-inverse"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    }
   },
   "resolved": {
    "Dark": "#F8FAFC"
   },
   "description": "Tooltips and inverse surfaces. Dark: gray/50."
  },
  {
   "figma": "Semantic::color/bg/overlay",
   "collection": "Semantic",
   "name": "color/bg/overlay",
   "type": "color",
   "css": "--color-bg-overlay",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-overlay"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::alpha/black-70"
    }
   },
   "resolved": {
    "Dark": "#000000B2"
   },
   "description": "Modal scrim (70% black). Dark: alpha/black-70."
  },
  {
   "figma": "Semantic::color/bg/error",
   "collection": "Semantic",
   "name": "color/bg/error",
   "type": "color",
   "css": "--color-bg-error",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-error"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/950"
    }
   },
   "resolved": {
    "Dark": "#450A0A"
   },
   "description": "Error banners and badges. Dark: red/950."
  },
  {
   "figma": "Semantic::color/bg/warning",
   "collection": "Semantic",
   "name": "color/bg/warning",
   "type": "color",
   "css": "--color-bg-warning",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-warning"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/950"
    }
   },
   "resolved": {
    "Dark": "#451A03"
   },
   "description": "Warning banners and badges. Dark: yellow/950."
  },
  {
   "figma": "Semantic::color/bg/success",
   "collection": "Semantic",
   "name": "color/bg/success",
   "type": "color",
   "css": "--color-bg-success",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-success"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::green/950"
    }
   },
   "resolved": {
    "Dark": "#022C22"
   },
   "description": "Success banners and badges. Dark: green/950."
  },
  {
   "figma": "Semantic::color/bg/info",
   "collection": "Semantic",
   "name": "color/bg/info",
   "type": "color",
   "css": "--color-bg-info",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-info"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::blue/950"
    }
   },
   "resolved": {
    "Dark": "#172554"
   },
   "description": "Info banners and badges. Dark: blue/950."
  },
  {
   "figma": "Semantic::color/bg/brand",
   "collection": "Semantic",
   "name": "color/bg/brand",
   "type": "color",
   "css": "--color-bg-brand",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-brand"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/600"
    }
   },
   "resolved": {
    "Dark": "#299B48"
   },
   "description": "Brand surfaces. Dark: brand/600."
  },
  {
   "figma": "Semantic::color/bg/brand-hover",
   "collection": "Semantic",
   "name": "color/bg/brand-hover",
   "type": "color",
   "css": "--color-bg-brand-hover",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-brand-hover"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/500"
    }
   },
   "resolved": {
    "Dark": "#39BD5D"
   },
   "description": "Brand surface hover. Dark: brand/500."
  },
  {
   "figma": "Semantic::color/bg/brand-active",
   "collection": "Semantic",
   "name": "color/bg/brand-active",
   "type": "color",
   "css": "--color-bg-brand-active",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-bg-brand-active"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/400"
    }
   },
   "resolved": {
    "Dark": "#59D77F"
   },
   "description": "Brand surface pressed. Dark: brand/400."
  },
  {
   "figma": "Semantic::color/border/default",
   "collection": "Semantic",
   "name": "color/border/default",
   "type": "color",
   "css": "--color-border-default",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-default"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/700"
    }
   },
   "resolved": {
    "Dark": "#334155"
   },
   "description": "Card and divider borders. Dark: gray/700."
  },
  {
   "figma": "Semantic::color/border/muted",
   "collection": "Semantic",
   "name": "color/border/muted",
   "type": "color",
   "css": "--color-border-muted",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-muted"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    }
   },
   "resolved": {
    "Dark": "#1E293B"
   },
   "description": "Subtle separators. Dark: gray/800."
  },
  {
   "figma": "Semantic::color/border/strong",
   "collection": "Semantic",
   "name": "color/border/strong",
   "type": "color",
   "css": "--color-border-strong",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-strong"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/400"
    }
   },
   "resolved": {
    "Dark": "#94A3B8"
   },
   "description": "Emphasized borders and the Hover border of inputs and controls (visible step up from border/input). Dark: gray/400."
  },
  {
   "figma": "Semantic::color/border/input",
   "collection": "Semantic",
   "name": "color/border/input",
   "type": "color",
   "css": "--color-border-input",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-input"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/500"
    }
   },
   "resolved": {
    "Dark": "#64748B"
   },
   "description": "Input borders (3.7:1 on bg/secondary). Dark: gray/500."
  },
  {
   "figma": "Semantic::color/border/inverse",
   "collection": "Semantic",
   "name": "color/border/inverse",
   "type": "color",
   "css": "--color-border-inverse",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-inverse"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    }
   },
   "resolved": {
    "Dark": "#F8FAFC"
   },
   "description": "Borders on inverse surfaces. Dark: gray/50."
  },
  {
   "figma": "Semantic::color/border/focus",
   "collection": "Semantic",
   "name": "color/border/focus",
   "type": "color",
   "css": "--color-border-focus",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-focus"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/400"
    }
   },
   "resolved": {
    "Dark": "#59D77F"
   },
   "description": "Focus rings. Dark: brand/400."
  },
  {
   "figma": "Semantic::color/border/error",
   "collection": "Semantic",
   "name": "color/border/error",
   "type": "color",
   "css": "--color-border-error",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-error"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/500"
    }
   },
   "resolved": {
    "Dark": "#EF4444"
   },
   "description": "Error input borders. Dark: red/500."
  },
  {
   "figma": "Semantic::color/border/warning",
   "collection": "Semantic",
   "name": "color/border/warning",
   "type": "color",
   "css": "--color-border-warning",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-warning"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/500"
    }
   },
   "resolved": {
    "Dark": "#F59E0B"
   },
   "description": "Warning borders. Dark: yellow/500."
  },
  {
   "figma": "Semantic::color/border/success",
   "collection": "Semantic",
   "name": "color/border/success",
   "type": "color",
   "css": "--color-border-success",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-success"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::green/500"
    }
   },
   "resolved": {
    "Dark": "#10B981"
   },
   "description": "Success input borders. Dark: green/500."
  },
  {
   "figma": "Semantic::color/border/brand",
   "collection": "Semantic",
   "name": "color/border/brand",
   "type": "color",
   "css": "--color-border-brand",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-border-brand"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/500"
    }
   },
   "resolved": {
    "Dark": "#39BD5D"
   },
   "description": "Selected and brand borders. Dark: brand/500."
  },
  {
   "figma": "Semantic::color/icon/default",
   "collection": "Semantic",
   "name": "color/icon/default",
   "type": "color",
   "css": "--color-icon-default",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-default"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/300"
    }
   },
   "resolved": {
    "Dark": "#CBD5E1"
   },
   "description": "Default icons. Dark: gray/300."
  },
  {
   "figma": "Semantic::color/icon/strong",
   "collection": "Semantic",
   "name": "color/icon/strong",
   "type": "color",
   "css": "--color-icon-strong",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-strong"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    }
   },
   "resolved": {
    "Dark": "#F8FAFC"
   },
   "description": "High emphasis icons. Dark: gray/50."
  },
  {
   "figma": "Semantic::color/icon/muted",
   "collection": "Semantic",
   "name": "color/icon/muted",
   "type": "color",
   "css": "--color-icon-muted",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-muted"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/400"
    }
   },
   "resolved": {
    "Dark": "#94A3B8"
   },
   "description": "Low emphasis icons. Dark: gray/400."
  },
  {
   "figma": "Semantic::color/icon/brand",
   "collection": "Semantic",
   "name": "color/icon/brand",
   "type": "color",
   "css": "--color-icon-brand",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-brand"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/400"
    }
   },
   "resolved": {
    "Dark": "#59D77F"
   },
   "description": "Brand icons, selected state. Dark: brand/400."
  },
  {
   "figma": "Semantic::color/icon/inverse",
   "collection": "Semantic",
   "name": "color/icon/inverse",
   "type": "color",
   "css": "--color-icon-inverse",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-inverse"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/950"
    }
   },
   "resolved": {
    "Dark": "#020617"
   },
   "description": "Icons on inverse surfaces. Dark: gray/950."
  },
  {
   "figma": "Semantic::color/icon/error",
   "collection": "Semantic",
   "name": "color/icon/error",
   "type": "color",
   "css": "--color-icon-error",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-error"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/400"
    }
   },
   "resolved": {
    "Dark": "#F87171"
   },
   "description": "Error icons. Dark: red/400."
  },
  {
   "figma": "Semantic::color/icon/warning",
   "collection": "Semantic",
   "name": "color/icon/warning",
   "type": "color",
   "css": "--color-icon-warning",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-warning"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::yellow/400"
    }
   },
   "resolved": {
    "Dark": "#FBBF24"
   },
   "description": "Warning icons. Dark: yellow/400."
  },
  {
   "figma": "Semantic::color/icon/success",
   "collection": "Semantic",
   "name": "color/icon/success",
   "type": "color",
   "css": "--color-icon-success",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-success"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::green/400"
    }
   },
   "resolved": {
    "Dark": "#34D399"
   },
   "description": "Success icons. Dark: green/400."
  },
  {
   "figma": "Semantic::color/icon/info",
   "collection": "Semantic",
   "name": "color/icon/info",
   "type": "color",
   "css": "--color-icon-info",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-icon-info"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::blue/400"
    }
   },
   "resolved": {
    "Dark": "#60A5FA"
   },
   "description": "Info icons. Dark: blue/400."
  },
  {
   "figma": "Semantic::color/action/primary/bg",
   "collection": "Semantic",
   "name": "color/action/primary/bg",
   "type": "color",
   "css": "--color-action-primary-bg",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-primary-bg"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/600"
    }
   },
   "resolved": {
    "Dark": "#299B48"
   },
   "description": "Primary button bg. Dark: brand/600."
  },
  {
   "figma": "Semantic::color/action/primary/bg-hover",
   "collection": "Semantic",
   "name": "color/action/primary/bg-hover",
   "type": "color",
   "css": "--color-action-primary-bg-hover",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-primary-bg-hover"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/500"
    }
   },
   "resolved": {
    "Dark": "#39BD5D"
   },
   "description": "Primary button bg hover. Dark: brand/500."
  },
  {
   "figma": "Semantic::color/action/primary/bg-active",
   "collection": "Semantic",
   "name": "color/action/primary/bg-active",
   "type": "color",
   "css": "--color-action-primary-bg-active",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-primary-bg-active"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/400"
    }
   },
   "resolved": {
    "Dark": "#59D77F"
   },
   "description": "Primary button bg active. Dark: brand/400."
  },
  {
   "figma": "Semantic::color/action/primary/text",
   "collection": "Semantic",
   "name": "color/action/primary/text",
   "type": "color",
   "css": "--color-action-primary-text",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-primary-text"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/950"
    }
   },
   "resolved": {
    "Dark": "#020617"
   },
   "description": "Primary button text. Dark: gray/950."
  },
  {
   "figma": "Semantic::color/action/primary/border",
   "collection": "Semantic",
   "name": "color/action/primary/border",
   "type": "color",
   "css": "--color-action-primary-border",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-primary-border"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::brand/600"
    }
   },
   "resolved": {
    "Dark": "#299B48"
   },
   "description": "Primary button border. Dark: brand/600."
  },
  {
   "figma": "Semantic::color/action/secondary/bg",
   "collection": "Semantic",
   "name": "color/action/secondary/bg",
   "type": "color",
   "css": "--color-action-secondary-bg",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-secondary-bg"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/800"
    }
   },
   "resolved": {
    "Dark": "#1E293B"
   },
   "description": "Secondary button bg. Dark: gray/800."
  },
  {
   "figma": "Semantic::color/action/secondary/bg-hover",
   "collection": "Semantic",
   "name": "color/action/secondary/bg-hover",
   "type": "color",
   "css": "--color-action-secondary-bg-hover",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-secondary-bg-hover"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/700"
    }
   },
   "resolved": {
    "Dark": "#334155"
   },
   "description": "Secondary button bg hover. Dark: gray/700."
  },
  {
   "figma": "Semantic::color/action/secondary/bg-active",
   "collection": "Semantic",
   "name": "color/action/secondary/bg-active",
   "type": "color",
   "css": "--color-action-secondary-bg-active",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-secondary-bg-active"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/900"
    }
   },
   "resolved": {
    "Dark": "#0F172A"
   },
   "description": "Secondary button bg active. Dark: gray/900."
  },
  {
   "figma": "Semantic::color/action/secondary/text",
   "collection": "Semantic",
   "name": "color/action/secondary/text",
   "type": "color",
   "css": "--color-action-secondary-text",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-secondary-text"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/50"
    }
   },
   "resolved": {
    "Dark": "#F8FAFC"
   },
   "description": "Secondary button text. Dark: gray/50."
  },
  {
   "figma": "Semantic::color/action/secondary/border",
   "collection": "Semantic",
   "name": "color/action/secondary/border",
   "type": "color",
   "css": "--color-action-secondary-border",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-secondary-border"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::gray/500"
    }
   },
   "resolved": {
    "Dark": "#64748B"
   },
   "description": "Secondary (Outline) button border, 3:1 or more on bg/primary and bg/secondary. Dark: gray/500."
  },
  {
   "figma": "Semantic::color/action/danger/bg",
   "collection": "Semantic",
   "name": "color/action/danger/bg",
   "type": "color",
   "css": "--color-action-danger-bg",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-danger-bg"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/600"
    }
   },
   "resolved": {
    "Dark": "#DC2626"
   },
   "description": "Danger button bg. Dark: red/600."
  },
  {
   "figma": "Semantic::color/action/danger/bg-hover",
   "collection": "Semantic",
   "name": "color/action/danger/bg-hover",
   "type": "color",
   "css": "--color-action-danger-bg-hover",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-danger-bg-hover"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/700"
    }
   },
   "resolved": {
    "Dark": "#B91C1C"
   },
   "description": "Danger button bg hover. Dark: red/700."
  },
  {
   "figma": "Semantic::color/action/danger/bg-active",
   "collection": "Semantic",
   "name": "color/action/danger/bg-active",
   "type": "color",
   "css": "--color-action-danger-bg-active",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-danger-bg-active"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/800"
    }
   },
   "resolved": {
    "Dark": "#991B1B"
   },
   "description": "Danger button bg active. Dark: red/800."
  },
  {
   "figma": "Semantic::color/action/danger/text",
   "collection": "Semantic",
   "name": "color/action/danger/text",
   "type": "color",
   "css": "--color-action-danger-text",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-danger-text"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::white"
    }
   },
   "resolved": {
    "Dark": "#FFFFFF"
   },
   "description": "Danger button text. Dark: white."
  },
  {
   "figma": "Semantic::color/action/danger/border",
   "collection": "Semantic",
   "name": "color/action/danger/border",
   "type": "color",
   "css": "--color-action-danger-border",
   "code": [
    {
     "label": "CSS variable",
     "name": "--color-action-danger-border"
    }
   ],
   "values": {
    "Dark": {
     "alias": "Primitives::red/600"
    }
   },
   "resolved": {
    "Dark": "#DC2626"
   },
   "description": "Danger button border. Dark: red/600."
  },
  {
   "figma": "Spacing::space/0",
   "collection": "Spacing",
   "name": "space/0",
   "type": "number",
   "css": "--space-0",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-0"
    }
   ],
   "values": {
    "Desktop": 0,
    "iPad": 0,
    "Mobile": 0
   },
   "resolved": {},
   "description": "Tailwind p-0 / gap-0: 0px Desktop, 0 iPad, 0 Mobile."
  },
  {
   "figma": "Spacing::space/1",
   "collection": "Spacing",
   "name": "space/1",
   "type": "number",
   "css": "--space-1",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-1"
    }
   ],
   "values": {
    "Desktop": 4,
    "iPad": 4,
    "Mobile": 4
   },
   "resolved": {},
   "description": "Tailwind p-1 / gap-1: 4px Desktop, 4 iPad, 4 Mobile."
  },
  {
   "figma": "Spacing::space/2",
   "collection": "Spacing",
   "name": "space/2",
   "type": "number",
   "css": "--space-2",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-2"
    }
   ],
   "values": {
    "Desktop": 8,
    "iPad": 8,
    "Mobile": 8
   },
   "resolved": {},
   "description": "Tailwind p-2 / gap-2: 8px Desktop, 8 iPad, 8 Mobile."
  },
  {
   "figma": "Spacing::space/3",
   "collection": "Spacing",
   "name": "space/3",
   "type": "number",
   "css": "--space-3",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-3"
    }
   ],
   "values": {
    "Desktop": 12,
    "iPad": 12,
    "Mobile": 12
   },
   "resolved": {},
   "description": "Tailwind p-3 / gap-3: 12px Desktop, 12 iPad, 12 Mobile."
  },
  {
   "figma": "Spacing::space/4",
   "collection": "Spacing",
   "name": "space/4",
   "type": "number",
   "css": "--space-4",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-4"
    }
   ],
   "values": {
    "Desktop": 16,
    "iPad": 16,
    "Mobile": 16
   },
   "resolved": {},
   "description": "Tailwind p-4 / gap-4: 16px Desktop, 16 iPad, 16 Mobile."
  },
  {
   "figma": "Spacing::space/5",
   "collection": "Spacing",
   "name": "space/5",
   "type": "number",
   "css": "--space-5",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-5"
    }
   ],
   "values": {
    "Desktop": 20,
    "iPad": 20,
    "Mobile": 16
   },
   "resolved": {},
   "description": "Tailwind p-5 / gap-5: 20px Desktop, 20 iPad, 16 Mobile."
  },
  {
   "figma": "Spacing::space/6",
   "collection": "Spacing",
   "name": "space/6",
   "type": "number",
   "css": "--space-6",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-6"
    }
   ],
   "values": {
    "Desktop": 24,
    "iPad": 22,
    "Mobile": 18
   },
   "resolved": {},
   "description": "Tailwind p-6 / gap-6: 24px Desktop, 22 iPad, 18 Mobile."
  },
  {
   "figma": "Spacing::space/7",
   "collection": "Spacing",
   "name": "space/7",
   "type": "number",
   "css": "--space-7",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-7"
    }
   ],
   "values": {
    "Desktop": 28,
    "iPad": 26,
    "Mobile": 22
   },
   "resolved": {},
   "description": "Tailwind p-7 / gap-7: 28px Desktop, 26 iPad, 22 Mobile."
  },
  {
   "figma": "Spacing::space/8",
   "collection": "Spacing",
   "name": "space/8",
   "type": "number",
   "css": "--space-8",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-8"
    }
   ],
   "values": {
    "Desktop": 32,
    "iPad": 28,
    "Mobile": 24
   },
   "resolved": {},
   "description": "Tailwind p-8 / gap-8: 32px Desktop, 28 iPad, 24 Mobile."
  },
  {
   "figma": "Spacing::space/9",
   "collection": "Spacing",
   "name": "space/9",
   "type": "number",
   "css": "--space-9",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-9"
    }
   ],
   "values": {
    "Desktop": 36,
    "iPad": 32,
    "Mobile": 26
   },
   "resolved": {},
   "description": "Tailwind p-9 / gap-9: 36px Desktop, 32 iPad, 26 Mobile."
  },
  {
   "figma": "Spacing::space/10",
   "collection": "Spacing",
   "name": "space/10",
   "type": "number",
   "css": "--space-10",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-10"
    }
   ],
   "values": {
    "Desktop": 40,
    "iPad": 36,
    "Mobile": 28
   },
   "resolved": {},
   "description": "Tailwind p-10 / gap-10: 40px Desktop, 36 iPad, 28 Mobile."
  },
  {
   "figma": "Spacing::space/11",
   "collection": "Spacing",
   "name": "space/11",
   "type": "number",
   "css": "--space-11",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-11"
    }
   ],
   "values": {
    "Desktop": 44,
    "iPad": 40,
    "Mobile": 32
   },
   "resolved": {},
   "description": "Tailwind p-11 / gap-11: 44px Desktop, 40 iPad, 32 Mobile."
  },
  {
   "figma": "Spacing::space/12",
   "collection": "Spacing",
   "name": "space/12",
   "type": "number",
   "css": "--space-12",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-12"
    }
   ],
   "values": {
    "Desktop": 48,
    "iPad": 44,
    "Mobile": 32
   },
   "resolved": {},
   "description": "Tailwind p-12 / gap-12: 48px Desktop, 44 iPad, 32 Mobile."
  },
  {
   "figma": "Spacing::space/14",
   "collection": "Spacing",
   "name": "space/14",
   "type": "number",
   "css": "--space-14",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-14"
    }
   ],
   "values": {
    "Desktop": 56,
    "iPad": 48,
    "Mobile": 36
   },
   "resolved": {},
   "description": "Tailwind p-14 / gap-14: 56px Desktop, 48 iPad, 36 Mobile."
  },
  {
   "figma": "Spacing::space/16",
   "collection": "Spacing",
   "name": "space/16",
   "type": "number",
   "css": "--space-16",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-16"
    }
   ],
   "values": {
    "Desktop": 64,
    "iPad": 52,
    "Mobile": 40
   },
   "resolved": {},
   "description": "Tailwind p-16 / gap-16: 64px Desktop, 52 iPad, 40 Mobile."
  },
  {
   "figma": "Spacing::space/20",
   "collection": "Spacing",
   "name": "space/20",
   "type": "number",
   "css": "--space-20",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-20"
    }
   ],
   "values": {
    "Desktop": 80,
    "iPad": 64,
    "Mobile": 48
   },
   "resolved": {},
   "description": "Tailwind p-20 / gap-20: 80px Desktop, 64 iPad, 48 Mobile."
  },
  {
   "figma": "Spacing::space/24",
   "collection": "Spacing",
   "name": "space/24",
   "type": "number",
   "css": "--space-24",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-24"
    }
   ],
   "values": {
    "Desktop": 96,
    "iPad": 76,
    "Mobile": 56
   },
   "resolved": {},
   "description": "Tailwind p-24 / gap-24: 96px Desktop, 76 iPad, 56 Mobile."
  },
  {
   "figma": "Spacing::space/28",
   "collection": "Spacing",
   "name": "space/28",
   "type": "number",
   "css": "--space-28",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-28"
    }
   ],
   "values": {
    "Desktop": 112,
    "iPad": 88,
    "Mobile": 64
   },
   "resolved": {},
   "description": "Tailwind p-28 / gap-28: 112px Desktop, 88 iPad, 64 Mobile."
  },
  {
   "figma": "Spacing::space/32",
   "collection": "Spacing",
   "name": "space/32",
   "type": "number",
   "css": "--space-32",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-32"
    }
   ],
   "values": {
    "Desktop": 128,
    "iPad": 96,
    "Mobile": 72
   },
   "resolved": {},
   "description": "Tailwind p-32 / gap-32: 128px Desktop, 96 iPad, 72 Mobile."
  },
  {
   "figma": "Spacing::space/36",
   "collection": "Spacing",
   "name": "space/36",
   "type": "number",
   "css": "--space-36",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-36"
    }
   ],
   "values": {
    "Desktop": 144,
    "iPad": 112,
    "Mobile": 80
   },
   "resolved": {},
   "description": "Tailwind p-36 / gap-36: 144px Desktop, 112 iPad, 80 Mobile."
  },
  {
   "figma": "Spacing::space/40",
   "collection": "Spacing",
   "name": "space/40",
   "type": "number",
   "css": "--space-40",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-40"
    }
   ],
   "values": {
    "Desktop": 160,
    "iPad": 120,
    "Mobile": 88
   },
   "resolved": {},
   "description": "Tailwind p-40 / gap-40: 160px Desktop, 120 iPad, 88 Mobile."
  },
  {
   "figma": "Spacing::space/48",
   "collection": "Spacing",
   "name": "space/48",
   "type": "number",
   "css": "--space-48",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-48"
    }
   ],
   "values": {
    "Desktop": 192,
    "iPad": 144,
    "Mobile": 96
   },
   "resolved": {},
   "description": "Tailwind p-48 / gap-48: 192px Desktop, 144 iPad, 96 Mobile."
  },
  {
   "figma": "Spacing::space/56",
   "collection": "Spacing",
   "name": "space/56",
   "type": "number",
   "css": "--space-56",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-56"
    }
   ],
   "values": {
    "Desktop": 224,
    "iPad": 168,
    "Mobile": 104
   },
   "resolved": {},
   "description": "Tailwind p-56 / gap-56: 224px Desktop, 168 iPad, 104 Mobile."
  },
  {
   "figma": "Spacing::space/64",
   "collection": "Spacing",
   "name": "space/64",
   "type": "number",
   "css": "--space-64",
   "code": [
    {
     "label": "CSS variable",
     "name": "--space-64"
    }
   ],
   "values": {
    "Desktop": 256,
    "iPad": 192,
    "Mobile": 112
   },
   "resolved": {},
   "description": "Tailwind p-64 / gap-64: 256px Desktop, 192 iPad, 112 Mobile."
  },
  {
   "figma": "Radius::radius/none",
   "collection": "Radius",
   "name": "radius/none",
   "type": "number",
   "css": "--radius-none",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-none"
    }
   ],
   "values": {
    "Value": 0
   },
   "resolved": {},
   "description": "0px (Tailwind rounded-none). No rounding."
  },
  {
   "figma": "Radius::radius/sm",
   "collection": "Radius",
   "name": "radius/sm",
   "type": "number",
   "css": "--radius-sm",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-sm"
    }
   ],
   "values": {
    "Value": 2
   },
   "resolved": {},
   "description": "2px (Tailwind rounded-sm). Tags, tiny elements."
  },
  {
   "figma": "Radius::radius/base",
   "collection": "Radius",
   "name": "radius/base",
   "type": "number",
   "css": "--radius-base",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-base"
    }
   ],
   "values": {
    "Value": 4
   },
   "resolved": {},
   "description": "4px (Tailwind rounded). Checkboxes, small chips."
  },
  {
   "figma": "Radius::radius/md",
   "collection": "Radius",
   "name": "radius/md",
   "type": "number",
   "css": "--radius-md",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-md"
    }
   ],
   "values": {
    "Value": 6
   },
   "resolved": {},
   "description": "6px (Tailwind rounded-md). Buttons."
  },
  {
   "figma": "Radius::radius/lg",
   "collection": "Radius",
   "name": "radius/lg",
   "type": "number",
   "css": "--radius-lg",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-lg"
    }
   ],
   "values": {
    "Value": 8
   },
   "resolved": {},
   "description": "8px (Tailwind rounded-lg). Inputs, cards."
  },
  {
   "figma": "Radius::radius/xl",
   "collection": "Radius",
   "name": "radius/xl",
   "type": "number",
   "css": "--radius-xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-xl"
    }
   ],
   "values": {
    "Value": 12
   },
   "resolved": {},
   "description": "12px (Tailwind rounded-xl). Panels, popovers."
  },
  {
   "figma": "Radius::radius/2xl",
   "collection": "Radius",
   "name": "radius/2xl",
   "type": "number",
   "css": "--radius-2xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-2xl"
    }
   ],
   "values": {
    "Value": 16
   },
   "resolved": {},
   "description": "16px (Tailwind rounded-2xl). Modals, large cards."
  },
  {
   "figma": "Radius::radius/3xl",
   "collection": "Radius",
   "name": "radius/3xl",
   "type": "number",
   "css": "--radius-3xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-3xl"
    }
   ],
   "values": {
    "Value": 24
   },
   "resolved": {},
   "description": "24px (Tailwind rounded-3xl). Hero surfaces."
  },
  {
   "figma": "Radius::radius/full",
   "collection": "Radius",
   "name": "radius/full",
   "type": "number",
   "css": "--radius-full",
   "code": [
    {
     "label": "CSS variable",
     "name": "--radius-full"
    }
   ],
   "values": {
    "Value": 9999
   },
   "resolved": {},
   "description": "9999px (Tailwind rounded-full). Pills, avatars, toggles."
  },
  {
   "figma": "Opacity::opacity/disabled",
   "collection": "Opacity",
   "name": "opacity/disabled",
   "type": "number",
   "css": "--opacity-disabled",
   "code": [
    {
     "label": "CSS variable",
     "name": "--opacity-disabled"
    }
   ],
   "values": {
    "Value": 50
   },
   "resolved": {},
   "description": "50% opacity for every disabled state (the component keeps its own colors)."
  },
  {
   "figma": "Typography::font-family/base",
   "collection": "Typography",
   "name": "font-family/base",
   "type": "string",
   "css": "--font-family-base",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-family-base"
    }
   ],
   "values": {
    "Desktop": "Poppins",
    "iPad": "Poppins",
    "Mobile": "Poppins"
   },
   "resolved": {},
   "description": "Poppins, the ClinicSoft system font (Latin only)."
  },
  {
   "figma": "Typography::font-weight/regular",
   "collection": "Typography",
   "name": "font-weight/regular",
   "type": "string",
   "css": "--font-weight-regular",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-weight-regular"
    }
   ],
   "values": {
    "Desktop": "Regular",
    "iPad": "Regular",
    "Mobile": "Regular"
   },
   "resolved": {},
   "description": "Poppins Regular (Tailwind font-normal)."
  },
  {
   "figma": "Typography::font-weight/medium",
   "collection": "Typography",
   "name": "font-weight/medium",
   "type": "string",
   "css": "--font-weight-medium",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-weight-medium"
    }
   ],
   "values": {
    "Desktop": "Medium",
    "iPad": "Medium",
    "Mobile": "Medium"
   },
   "resolved": {},
   "description": "Poppins Medium (Tailwind font-medium)."
  },
  {
   "figma": "Typography::font-weight/semibold",
   "collection": "Typography",
   "name": "font-weight/semibold",
   "type": "string",
   "css": "--font-weight-semibold",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-weight-semibold"
    }
   ],
   "values": {
    "Desktop": "SemiBold",
    "iPad": "SemiBold",
    "Mobile": "SemiBold"
   },
   "resolved": {},
   "description": "Poppins SemiBold (Tailwind font-semibold)."
  },
  {
   "figma": "Typography::font-weight/bold",
   "collection": "Typography",
   "name": "font-weight/bold",
   "type": "string",
   "css": "--font-weight-bold",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-weight-bold"
    }
   ],
   "values": {
    "Desktop": "Bold",
    "iPad": "Bold",
    "Mobile": "Bold"
   },
   "resolved": {},
   "description": "Poppins Bold (Tailwind font-bold)."
  },
  {
   "figma": "Typography::font-size/xs",
   "collection": "Typography",
   "name": "font-size/xs",
   "type": "number",
   "css": "--font-size-xs",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-xs"
    }
   ],
   "values": {
    "Desktop": 12,
    "iPad": 12,
    "Mobile": 12
   },
   "resolved": {},
   "description": "Tailwind text-xs: 12 / 12 / 12px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/sm",
   "collection": "Typography",
   "name": "font-size/sm",
   "type": "number",
   "css": "--font-size-sm",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-sm"
    }
   ],
   "values": {
    "Desktop": 14,
    "iPad": 14,
    "Mobile": 14
   },
   "resolved": {},
   "description": "Tailwind text-sm: 14 / 14 / 14px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/base",
   "collection": "Typography",
   "name": "font-size/base",
   "type": "number",
   "css": "--font-size-base",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-base"
    }
   ],
   "values": {
    "Desktop": 16,
    "iPad": 16,
    "Mobile": 16
   },
   "resolved": {},
   "description": "Tailwind text-base: 16 / 16 / 16px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/lg",
   "collection": "Typography",
   "name": "font-size/lg",
   "type": "number",
   "css": "--font-size-lg",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-lg"
    }
   ],
   "values": {
    "Desktop": 18,
    "iPad": 18,
    "Mobile": 18
   },
   "resolved": {},
   "description": "Tailwind text-lg: 18 / 18 / 18px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/xl",
   "collection": "Typography",
   "name": "font-size/xl",
   "type": "number",
   "css": "--font-size-xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-xl"
    }
   ],
   "values": {
    "Desktop": 20,
    "iPad": 20,
    "Mobile": 18
   },
   "resolved": {},
   "description": "Tailwind text-xl: 20 / 20 / 18px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/2xl",
   "collection": "Typography",
   "name": "font-size/2xl",
   "type": "number",
   "css": "--font-size-2xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-2xl"
    }
   ],
   "values": {
    "Desktop": 24,
    "iPad": 22,
    "Mobile": 20
   },
   "resolved": {},
   "description": "Tailwind text-2xl: 24 / 22 / 20px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/3xl",
   "collection": "Typography",
   "name": "font-size/3xl",
   "type": "number",
   "css": "--font-size-3xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-3xl"
    }
   ],
   "values": {
    "Desktop": 28,
    "iPad": 24,
    "Mobile": 24
   },
   "resolved": {},
   "description": "Tailwind text-3xl: 28 / 24 / 24px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/4xl",
   "collection": "Typography",
   "name": "font-size/4xl",
   "type": "number",
   "css": "--font-size-4xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-4xl"
    }
   ],
   "values": {
    "Desktop": 32,
    "iPad": 28,
    "Mobile": 28
   },
   "resolved": {},
   "description": "Tailwind text-4xl: 32 / 28 / 28px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/5xl",
   "collection": "Typography",
   "name": "font-size/5xl",
   "type": "number",
   "css": "--font-size-5xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-5xl"
    }
   ],
   "values": {
    "Desktop": 40,
    "iPad": 36,
    "Mobile": 32
   },
   "resolved": {},
   "description": "Tailwind text-5xl: 40 / 36 / 32px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::font-size/6xl",
   "collection": "Typography",
   "name": "font-size/6xl",
   "type": "number",
   "css": "--font-size-6xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--font-size-6xl"
    }
   ],
   "values": {
    "Desktop": 48,
    "iPad": 44,
    "Mobile": 40
   },
   "resolved": {},
   "description": "Tailwind text-6xl: 48 / 44 / 40px (Desktop / iPad / Mobile)."
  },
  {
   "figma": "Typography::line-height/xs",
   "collection": "Typography",
   "name": "line-height/xs",
   "type": "number",
   "css": "--line-height-xs",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-xs"
    }
   ],
   "values": {
    "Desktop": 16,
    "iPad": 16,
    "Mobile": 16
   },
   "resolved": {},
   "description": "Line height for text-xs: 16 / 16 / 16px."
  },
  {
   "figma": "Typography::line-height/sm",
   "collection": "Typography",
   "name": "line-height/sm",
   "type": "number",
   "css": "--line-height-sm",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-sm"
    }
   ],
   "values": {
    "Desktop": 20,
    "iPad": 20,
    "Mobile": 20
   },
   "resolved": {},
   "description": "Line height for text-sm: 20 / 20 / 20px."
  },
  {
   "figma": "Typography::line-height/base",
   "collection": "Typography",
   "name": "line-height/base",
   "type": "number",
   "css": "--line-height-base",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-base"
    }
   ],
   "values": {
    "Desktop": 24,
    "iPad": 24,
    "Mobile": 24
   },
   "resolved": {},
   "description": "Line height for text-base: 24 / 24 / 24px."
  },
  {
   "figma": "Typography::line-height/lg",
   "collection": "Typography",
   "name": "line-height/lg",
   "type": "number",
   "css": "--line-height-lg",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-lg"
    }
   ],
   "values": {
    "Desktop": 28,
    "iPad": 28,
    "Mobile": 28
   },
   "resolved": {},
   "description": "Line height for text-lg: 28 / 28 / 28px."
  },
  {
   "figma": "Typography::line-height/xl",
   "collection": "Typography",
   "name": "line-height/xl",
   "type": "number",
   "css": "--line-height-xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-xl"
    }
   ],
   "values": {
    "Desktop": 28,
    "iPad": 28,
    "Mobile": 26
   },
   "resolved": {},
   "description": "Line height for text-xl: 28 / 28 / 26px."
  },
  {
   "figma": "Typography::line-height/2xl",
   "collection": "Typography",
   "name": "line-height/2xl",
   "type": "number",
   "css": "--line-height-2xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-2xl"
    }
   ],
   "values": {
    "Desktop": 32,
    "iPad": 30,
    "Mobile": 28
   },
   "resolved": {},
   "description": "Line height for text-2xl: 32 / 30 / 28px."
  },
  {
   "figma": "Typography::line-height/3xl",
   "collection": "Typography",
   "name": "line-height/3xl",
   "type": "number",
   "css": "--line-height-3xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-3xl"
    }
   ],
   "values": {
    "Desktop": 36,
    "iPad": 34,
    "Mobile": 32
   },
   "resolved": {},
   "description": "Line height for text-3xl: 36 / 34 / 32px."
  },
  {
   "figma": "Typography::line-height/4xl",
   "collection": "Typography",
   "name": "line-height/4xl",
   "type": "number",
   "css": "--line-height-4xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-4xl"
    }
   ],
   "values": {
    "Desktop": 40,
    "iPad": 38,
    "Mobile": 36
   },
   "resolved": {},
   "description": "Line height for text-4xl: 40 / 38 / 36px."
  },
  {
   "figma": "Typography::line-height/5xl",
   "collection": "Typography",
   "name": "line-height/5xl",
   "type": "number",
   "css": "--line-height-5xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-5xl"
    }
   ],
   "values": {
    "Desktop": 48,
    "iPad": 44,
    "Mobile": 40
   },
   "resolved": {},
   "description": "Line height for text-5xl: 48 / 44 / 40px."
  },
  {
   "figma": "Typography::line-height/6xl",
   "collection": "Typography",
   "name": "line-height/6xl",
   "type": "number",
   "css": "--line-height-6xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--line-height-6xl"
    }
   ],
   "values": {
    "Desktop": 60,
    "iPad": 56,
    "Mobile": 48
   },
   "resolved": {},
   "description": "Line height for text-6xl: 60 / 56 / 48px."
  },
  {
   "figma": "Typography::letter-spacing/xs",
   "collection": "Typography",
   "name": "letter-spacing/xs",
   "type": "number",
   "css": "--letter-spacing-xs",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-xs"
    }
   ],
   "values": {
    "Desktop": 0.20000000298023224,
    "iPad": 0.20000000298023224,
    "Mobile": 0.20000000298023224
   },
   "resolved": {},
   "description": "Tracking for text-xs: 0.2px."
  },
  {
   "figma": "Typography::letter-spacing/sm",
   "collection": "Typography",
   "name": "letter-spacing/sm",
   "type": "number",
   "css": "--letter-spacing-sm",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-sm"
    }
   ],
   "values": {
    "Desktop": 0,
    "iPad": 0,
    "Mobile": 0
   },
   "resolved": {},
   "description": "Tracking for text-sm: 0px."
  },
  {
   "figma": "Typography::letter-spacing/base",
   "collection": "Typography",
   "name": "letter-spacing/base",
   "type": "number",
   "css": "--letter-spacing-base",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-base"
    }
   ],
   "values": {
    "Desktop": 0,
    "iPad": 0,
    "Mobile": 0
   },
   "resolved": {},
   "description": "Tracking for text-base: 0px."
  },
  {
   "figma": "Typography::letter-spacing/lg",
   "collection": "Typography",
   "name": "letter-spacing/lg",
   "type": "number",
   "css": "--letter-spacing-lg",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-lg"
    }
   ],
   "values": {
    "Desktop": -0.20000000298023224,
    "iPad": -0.20000000298023224,
    "Mobile": -0.20000000298023224
   },
   "resolved": {},
   "description": "Tracking for text-lg: -0.2px."
  },
  {
   "figma": "Typography::letter-spacing/xl",
   "collection": "Typography",
   "name": "letter-spacing/xl",
   "type": "number",
   "css": "--letter-spacing-xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-xl"
    }
   ],
   "values": {
    "Desktop": -0.20000000298023224,
    "iPad": -0.20000000298023224,
    "Mobile": -0.20000000298023224
   },
   "resolved": {},
   "description": "Tracking for text-xl: -0.2px."
  },
  {
   "figma": "Typography::letter-spacing/2xl",
   "collection": "Typography",
   "name": "letter-spacing/2xl",
   "type": "number",
   "css": "--letter-spacing-2xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-2xl"
    }
   ],
   "values": {
    "Desktop": -0.4000000059604645,
    "iPad": -0.4000000059604645,
    "Mobile": -0.4000000059604645
   },
   "resolved": {},
   "description": "Tracking for text-2xl: -0.4px."
  },
  {
   "figma": "Typography::letter-spacing/3xl",
   "collection": "Typography",
   "name": "letter-spacing/3xl",
   "type": "number",
   "css": "--letter-spacing-3xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-3xl"
    }
   ],
   "values": {
    "Desktop": -0.6000000238418579,
    "iPad": -0.6000000238418579,
    "Mobile": -0.6000000238418579
   },
   "resolved": {},
   "description": "Tracking for text-3xl: -0.6px."
  },
  {
   "figma": "Typography::letter-spacing/4xl",
   "collection": "Typography",
   "name": "letter-spacing/4xl",
   "type": "number",
   "css": "--letter-spacing-4xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-4xl"
    }
   ],
   "values": {
    "Desktop": -0.800000011920929,
    "iPad": -0.800000011920929,
    "Mobile": -0.800000011920929
   },
   "resolved": {},
   "description": "Tracking for text-4xl: -0.8px."
  },
  {
   "figma": "Typography::letter-spacing/5xl",
   "collection": "Typography",
   "name": "letter-spacing/5xl",
   "type": "number",
   "css": "--letter-spacing-5xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-5xl"
    }
   ],
   "values": {
    "Desktop": -1,
    "iPad": -1,
    "Mobile": -1
   },
   "resolved": {},
   "description": "Tracking for text-5xl: -1px."
  },
  {
   "figma": "Typography::letter-spacing/6xl",
   "collection": "Typography",
   "name": "letter-spacing/6xl",
   "type": "number",
   "css": "--letter-spacing-6xl",
   "code": [
    {
     "label": "CSS variable",
     "name": "--letter-spacing-6xl"
    }
   ],
   "values": {
    "Desktop": -1.2000000476837158,
    "iPad": -1.2000000476837158,
    "Mobile": -1.2000000476837158
   },
   "resolved": {},
   "description": "Tracking for text-6xl: -1.2px."
  }
 ]
} as const;
export default tokens;
