// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Checkbox } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Checkbox",
  component: Checkbox,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Checked": {
    "control": "inline-radio",
    "options": [
      "Unchecked",
      "Checked",
      "Indeterminate"
    ],
    "description": "Figma variant property `Checked`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Unchecked"
      }
    }
  },
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Focus",
      "Error",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Label"
      }
    }
  },
  "Show Label": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Checked": "Unchecked", "State": "Default", "Label": "Label", "Show Label": true},
  parameters: {
    figma: { name: "Checkbox", page: "➜ Checkboxes", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2781" },
    docs: { description: { component: "**Figma:** `Checkbox` on page `➜ Checkboxes` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2781)\n\n**Tier:** Atom\n\n**Use:** Multi-select and consent choices that apply on submit. Not for instant settings (Toggle) or one-of-many (Radio).\n\n**Figma description:**\n\n> Atom. Purpose: select one or more independent options (consent, filters, \"send reminder by SMS\").  \n> Usage rules: use for multi-select and single on/off choices that take effect on submit; use Indeterminate only on a parent whose children are partly selected; use Error when a required box (e.g. consent) is not checked, with the message shown by the form. For an immediate on/off setting use Toggle; for one choice out of several use Radio.  \n> Accessibility: box 20px, whole row (box + label) is the click target (min 24px high); unchecked border color/border/input (3.7:1); Focus shows focus-ring-offset on the box; label is required unless the context labels it.  \n\n**When to use:** consent (\"I agree to share records with the referring doctor\"), table filters, \"Send reminder by SMS\" in a form saved with a button, \"Remember me\" on sign in.\n\n**When not to use:** for a setting that applies immediately (**Toggle**); for one choice out of several (**Radio**); for 5+ options where space is tight (**Select / Dropdown**).\n\n**Built from:** `Icon/Check`, `Icon/Minus`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Unchecked: Story = { name: "Unchecked", args: { "Checked": "Unchecked" } };
export const Checked: Story = { name: "Checked", args: { "Checked": "Checked" } };
export const Indeterminate: Story = { name: "Indeterminate", args: { "Checked": "Indeterminate" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateError: Story = { name: "State=Error", args: { "State": "Error" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Error", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Checkbox {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Unchecked", "Checked", "Indeterminate"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Checked={x}</div>
          <div className="sb-row">{["Default", "Hover", "Focus", "Error", "Disabled"].map((y) => <Checkbox key={y} {...args} {...{ "Checked": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
