// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { InputPhone } from '../../components/FormElements';
import { iconNames } from '../../lib/Icon';

const meta = {
  title: "Form Elements/Input / Phone",
  component: InputPhone,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Focus",
      "Filled",
      "Error",
      "Success",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Phone number"
      }
    }
  },
  "Show Optional": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Info": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Hint": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "As written on the ID card"
      }
    }
  },
  "Show Hint": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Helper text"
      }
    }
  },
  "Show Message": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Leading Icon": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Leading Icon": {
    "control": "select",
    "options": iconNames,
    "description": "Figma instance swap (Icon component)",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Icon/Phone"
      }
    }
  },
  "Placeholder": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "50 123 4567"
      }
    }
  },
  "Value": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "50 123 4567"
      }
    }
  },
  "Error Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Enter a valid mobile number"
      }
    }
  },
  "Success Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Looks good"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Phone number", "Show Optional": false, "Show Info": false, "Hint": "As written on the ID card", "Show Hint": false, "Message": "Helper text", "Show Message": false, "Show Leading Icon": true, "Leading Icon": "Icon/Phone", "Placeholder": "50 123 4567", "Value": "50 123 4567", "Error Message": "Enter a valid mobile number", "Success Message": "Looks good"},
  parameters: {
    figma: { name: "Input / Phone", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3828" },
    docs: { description: { component: "**Figma:** `Input / Phone` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3828)\n\n**Tier:** Molecule\n\n**Use:** Phone numbers with a country code prefix (default +971).\n\n**Figma description:**\n\n> Molecule (Label, Hint, field with Icon atoms, Message). Purpose: phone numbers with a country code prefix (default +971).  \n> Usage rules: always show a Label; Hint sits between the label and the field and explains the format; the Message row below the field shows helper text, or the error/success message in those states; use Show Optional instead of asterisks for optional fields; Filled shows a value, Default shows the placeholder (never use the placeholder as the label).  \n> Accessibility: field 40px high, border color/border/input (3.7:1 on bg/secondary), Focus 2px color/border/focus; placeholder color/text/placeholder (7:1); errors use icon + text, never color alone; label is linked to the field (for/id) and the message with aria-describedby in code.  \n\n**When to use:** patient and emergency-contact phone numbers, SMS reminder numbers.\n\n**When not to use:** other numbers (**Input / Text** or **Stepper**).\n\n**Built from:** `Icon/Chevron Down`, `Icon/Phone`, `Icon/Alert Circle`, `Icon/Check Circle`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof InputPhone>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Success: Story = { name: "Success", args: { "State": "Success" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Filled", "Error", "Success", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <InputPhone {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
