// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { InputDate } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Input / Date",
  component: InputDate,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Focus",
      "Filled",
      "Error",
      "Success",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Date of birth"
      }
    }
  },
  "Show Optional": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Show Info": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Hint": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "As written on the ID card"
      }
    }
  },
  "Show Hint": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Helper text"
      }
    }
  },
  "Show Message": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "false"
      }
    }
  },
  "Placeholder": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "DD/MM/YYYY"
      }
    }
  },
  "Value": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "12/03/2026"
      }
    }
  },
  "Error Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Enter a date in DD/MM/YYYY format"
      }
    }
  },
  "Success Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Looks good"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Date of birth", "Show Optional": false, "Show Info": false, "Hint": "As written on the ID card", "Show Hint": false, "Message": "Helper text", "Show Message": false, "Placeholder": "DD/MM/YYYY", "Value": "12/03/2026", "Error Message": "Enter a date in DD/MM/YYYY format", "Success Message": "Looks good"},
  parameters: {
    figma: { name: "Input / Date", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3688" },
    docs: { description: { component: "**Figma:** `Input / Date` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3688)\n\n**Tier:** Molecule\n\n**Use:** Dates (DD/MM/YYYY) such as date of birth or visit date; the calendar icon opens a picker in code.\n\n**Figma description:**\n\n> Molecule (Label, Hint, field with Icon atoms, Message). Purpose: dates such as date of birth or visit date; the calendar icon opens a date picker in code.  \n> Usage rules: always show a Label; Hint sits between the label and the field and explains the format; the Message row below the field shows helper text, or the error/success message in those states; use Show Optional instead of asterisks for optional fields; Filled shows a value, Default shows the placeholder (never use the placeholder as the label).  \n> Accessibility: field 40px high, border color/border/input (3.7:1 on bg/secondary), Focus 2px color/border/focus; placeholder color/text/placeholder (7:1); errors use icon + text, never color alone; label is linked to the field (for/id) and the message with aria-describedby in code.  \n\n**When to use:** date of birth, visit date, prescription start date.\n\n**When not to use:** a time only (no Time input; use **Select / Dropdown** with time slots, as in the Modal); a date range (not built).\n\n**Built from:** `Icon/Calendar`, `Icon/Alert Circle`, `Icon/Check Circle`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof InputDate>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Success: Story = { name: "Success", args: { "State": "Success" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Filled", "Error", "Success", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <InputDate {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Filled", "Error", "Success", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <InputDate {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
