// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { OTPCell } from '../../components/FormElements';

const meta = {
  title: "Form Elements/OTP / Cell",
  component: OTPCell,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Focus",
      "Filled",
      "Error",
      "Disabled",
      "Hover",
      "Success"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Digit": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "4"
      }
    }
  }
},
  args: {"State": "Default", "Digit": "4"},
  parameters: {
    figma: { name: "OTP / Cell", page: "➜ Input Fields and Dropdown", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3274" },
    docs: { description: { component: "**Figma:** `OTP / Cell` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3274)\n\n**Tier:** Atom\n\n**Use:** One digit box of a one-time code; only inside OTP / Field. Digit hidden in Default and Focus.\n\n**Figma description:**\n\n> Atom. Purpose: one digit box of a one-time code (patient login, prescription pickup verification).  \n> Usage rules: used only inside OTP / Field (4 or 6 cells); Filled once a digit is typed; Error on the whole row when the code is wrong; Focus moves to the next cell automatically in code.  \n> Accessibility: 48x56 cells; border color/border/input (3.7:1), Focus 2px color/border/focus; the field supports paste and one-time-code autofill in code.  \n\n**When to use:** only inside **OTP / Field**.\n\n**When not to use:** alone, or as a small number input (**Stepper** or **Input / Text**).\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof OTPCell>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Success: Story = { name: "Success", args: { "State": "Success" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Focus", "Filled", "Error", "Disabled", "Hover", "Success"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <OTPCell {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Focus", "Filled", "Error", "Disabled", "Hover", "Success"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <OTPCell {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
