// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { OTPField } from '../../components/FormElements';

const meta = {
  title: "Form Elements/OTP / Field",
  component: OTPField,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Filled",
      "Error",
      "Disabled",
      "Success"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Verification code"
      }
    }
  },
  "Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Sent to +971 50 ••• 4567"
      }
    }
  },
  "Error Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "The code is incorrect. Try again."
      }
    }
  },
  "Success Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Code verified"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Verification code", "Message": "Sent to +971 50 ••• 4567", "Error Message": "The code is incorrect. Try again.", "Success Message": "Code verified"},
  parameters: {
    figma: { name: "OTP / Field", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-4065" },
    docs: { description: { component: "**Figma:** `OTP / Field` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-4065)\n\n**Tier:** Molecule\n\n**Use:** Enter a one-time code (patient login, prescription pickup). 6 cells; hide cells 5-6 for 4-digit codes.\n\n**Figma description:**\n\n> Molecule (6 OTP / Cell atoms, label, message). Purpose: enter a one-time code (patient login, prescription pickup).  \n> Usage rules: 6 cells by default (hide cells 5-6 for 4-digit codes); Default has focus on the first empty cell; Error marks every cell and explains what to do; offer \"Resend code\" with a Link Button below in screens.  \n> Accessibility: supports paste and autocomplete=\"one-time-code\" in code; each cell 48x56; errors in text, not color alone.  \n\n**When to use:** patient login, prescription pickup verification, two-step sign in.\n\n**When not to use:** passwords (**Input / Password**) or other numbers.\n\n**Built from:** `OTP / Cell`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof OTPField>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Success: Story = { name: "Success", args: { "State": "Success" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Filled", "Error", "Disabled", "Success"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <OTPField {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
