// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Radio, RadioGroup } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Radio",
  component: Radio,
  tags: ['!autodocs', 'tier-atom'],
  argTypes: {
  "Selected": {
    "control": "inline-radio",
    "options": [
      "Off",
      "On"
    ],
    "description": "Figma variant property `Selected`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Off"
      }
    }
  },
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Focus",
      "Error",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Label"
      }
    }
  },
  "Show Label": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Selected": "Off", "State": "Default", "Label": "Label", "Show Label": true},
  parameters: {
    figma: { name: "Radio", page: "➜ Radio Buttons", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2833" },
    docs: { description: { component: "**Figma:** `Radio` on page `➜ Radio Buttons` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2833)\n\n**Tier:** Atom\n\n**Use:** Exactly one choice from 2-6 visible options (visit type, payment method). 5+ options -> Select / Dropdown.\n\n**Figma description:**\n\n> Atom. Purpose: choose exactly one option from a short list (visit type: In person / Video; payment method).  \n> Usage rules: always in a group of 2 to 6 options with one pre-selected when a safe default exists; more than 6 options -> Select / Dropdown; independent choices -> Checkbox; instant on/off -> Toggle. Error marks a required group with no choice.  \n> Accessibility: circle 20px, the whole row is the click target (min 24px high); unselected border color/border/input (3.7:1); arrow keys move within the group in code; Focus shows focus-ring-offset.  \n\n**When to use:** visit type (In person / Video), payment method, any single choice of 2-6 visible options.\n\n**When not to use:** 7+ options (**Select / Dropdown**); independent choices (**Checkbox**); on/off setting (**Toggle**); switching views (**Tabs / Bar** Segmented).\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Radio>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Off: Story = { name: "Off", args: { "Selected": "Off" } };
export const On: Story = { name: "On", args: { "Selected": "On" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateError: Story = { name: "State=Error", args: { "State": "Error" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Error", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Radio {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Off", "On"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Selected={x}</div>
          <div className="sb-row">{["Default", "Hover", "Focus", "Error", "Disabled"].map((y) => <Radio key={y} {...args} {...{ "Selected": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};

export const InUse: Story = { name: 'In use (interactive)', render: () => <RadioGroup /> };
