// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Search } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Search",
  component: Search,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Focus",
      "Filled",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Placeholder": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Search patients, doctors, files"
      }
    }
  }
},
  args: {"State": "Default", "Placeholder": "Search patients, doctors, files"},
  parameters: {
    figma: { name: "Search", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3937" },
    docs: { description: { component: "**Figma:** `Search` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3937)\n\n**Tier:** Molecule\n\n**Use:** Find records on the screen or across the app; Clear button when filled.\n\n**Figma description:**\n\n> Molecule (Search Icon, text, Clear Icon Button). Purpose: find records on the current screen or across the app (patients, appointments, files).  \n> Usage rules: placeholder says what can be searched; Clear appears only when there is text (Filled); results update as the user types or on Enter; do not use Search as a data-entry field.  \n> Accessibility: 40px high, pill shape; border color/border/input (3.7:1); Clear Icon Button needs aria-label \"Clear search\"; role=\"search\" on the container in code.  \n\n**When to use:** table and list search, the Top Bar global search.\n\n**When not to use:** to pick one value for a form (**Select / Dropdown**); as a data-entry field.\n\n**Built from:** `Icon/Search`, `Icon Button`, `Icon/Close`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Search>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Filled", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Search {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Filled", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Search {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
