// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { SelectDropdown } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Select / Dropdown",
  component: SelectDropdown,
  tags: ['autodocs', 'tier-organism'],
  argTypes: {
  "Open": {
    "control": "inline-radio",
    "options": [
      "False",
      "True"
    ],
    "description": "Figma variant property `Open`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "False"
      }
    }
  },
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Filled",
      "Error",
      "Disabled",
      "Focus",
      "Success"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Doctor"
      }
    }
  },
  "Placeholder": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Choose a doctor"
      }
    }
  },
  "Value": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Dr. Dana Khalil"
      }
    }
  },
  "Error Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Choose a doctor to continue"
      }
    }
  }
},
  args: {"Open": "False", "State": "Default", "Label": "Doctor", "Placeholder": "Choose a doctor", "Value": "Dr. Dana Khalil", "Error Message": "Choose a doctor to continue"},
  parameters: {
    figma: { name: "Select / Dropdown", page: "➜ Input Fields and Dropdown", tier: "Organism", order: 3 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=9-4673" },
    docs: { description: { component: "**Figma:** `Select / Dropdown` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=9-4673)\n\n**Tier:** Organism\n\n**Use:** Pick one value from a list of 7 or more (doctor, branch, insurer, time slot); Radio for 2 to 6 visible options (Abdul, 2026-09-30). Open=True exists only with State=Focus.\n\n**Figma description:**\n\n> Organism (field, Icon, Menu molecule with Menu / Item atoms, exposed). Purpose: pick one value from a list of 5 or more (doctor, clinic branch, insurance provider, specialty).  \n> Usage rules: use Radio for 2 to 5 visible options; placeholder says what to choose; Open shows the Menu with the current value Selected (check icon); add Search at the top of the menu in code when the list is long; Error explains what is missing.  \n> Accessibility: 40px field, border color/border/input (3.7:1), Focus 2px color/border/focus; role=\"combobox\"/\"listbox\" with arrow keys, Enter and Escape in code; selected option marked with a check, not color only.  \n\n**When to use:** doctor, clinic branch, insurance provider, specialty, time slot.\n\n**When not to use:** 2-6 options (**Radio**); actions (**Menu**); multi-select (not built); free text (**Input / Text**).\n\n**Built from:** `Menu`, `Menu / Item`, `Icon/Chevron Down`, `Icon/Chevron Up`, `Icon/Check`, `Icon/Alert Circle`, `Icon/Check Circle`\n\n**Known Figma gaps (see gaps.md):** Figma description still says Radio for 2 to 5; update it to 2 to 6 in the DS file and republish (decided 2026-09-30)\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof SelectDropdown>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const False: Story = { name: "False", args: { "Open": "False" } };
export const True: Story = { name: "True", args: { "Open": "True" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StateFilled: Story = { name: "State=Filled", args: { "State": "Filled" } };
export const StateError: Story = { name: "State=Error", args: { "State": "Error" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateSuccess: Story = { name: "State=Success", args: { "State": "Success" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Filled", "Error", "Disabled", "Focus", "Success"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <SelectDropdown {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
