// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Stepper } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Stepper",
  component: Stepper,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Min",
      "Max",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Value": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "2"
      }
    }
  }
},
  args: {"State": "Default", "Value": "2"},
  parameters: {
    figma: { name: "Stepper", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-4121" },
    docs: { description: { component: "**Figma:** `Stepper` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-4121)\n\n**Tier:** Molecule\n\n**Use:** Change a small whole number (tablets per dose, refills); ranges up to about 20.\n\n**Figma description:**\n\n> Molecule (2 Icon Button atoms + value box). Purpose: change a small whole number (tablets per dose, refills, number of guests).  \n> Usage rules: use for ranges up to about 20; Min and Max disable the button that would leave the range; for larger or free numbers use Input / Text with a number keyboard.  \n> Accessibility: 40x40 buttons with aria-labels (\"Decrease\", \"Increase\"); value is announced (role=\"spinbutton\" with aria-valuemin/max in code).  \n\n**When to use:** tablets per dose, refills, number of companions.\n\n**When not to use:** large or free numbers (**Input / Text** with a number keyboard); named options (**Select / Dropdown**).\n\n**Built from:** `Icon Button`, `Icon/Minus`, `Icon/Add`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Stepper>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Min: Story = { name: "Min", args: { "State": "Min" } };
export const Max: Story = { name: "Max", args: { "State": "Max" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Min", "Max", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Stepper {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Min", "Max", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <Stepper {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
