// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { TextArea } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Text Area",
  component: TextArea,
  tags: ['autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Focus",
      "Filled",
      "Error",
      "Disabled",
      "Success"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Visit notes"
      }
    }
  },
  "Show Character Count": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Show Message": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  },
  "Placeholder": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Write clinical notes…"
      }
    }
  },
  "Value": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Patient reports mild headache for three days. No fever."
      }
    }
  },
  "Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Visible to the care team"
      }
    }
  },
  "Error Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Notes are required for this visit"
      }
    }
  },
  "Success Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Notes saved"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Visit notes", "Show Character Count": true, "Show Message": true, "Placeholder": "Write clinical notes…", "Value": "Patient reports mild headache for three days. No fever.", "Message": "Visible to the care team", "Error Message": "Notes are required for this visit", "Success Message": "Notes saved"},
  parameters: {
    figma: { name: "Text Area", page: "➜ Text Area", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3883" },
    docs: { description: { component: "**Figma:** `Text Area` on page `➜ Text Area` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-3883)\n\n**Tier:** Molecule\n\n**Use:** Multi-line text such as visit notes, symptoms, referral reasons.\n\n**Figma description:**\n\n> Molecule (Label, field, Message and Character Count). Purpose: multi-line text such as visit notes, symptoms, referral reasons.  \n> Usage rules: use when the answer can be longer than one line; show the character count when there is a limit; the message row shows helper text or the error; keep the label short.  \n> Accessibility: border color/border/input (3.7:1), Focus 2px color/border/focus; min height 120px; errors use text, not color alone; the count is announced politely in code.  \n\n**When to use:** visit notes, symptoms, referral reasons, comments.\n\n**When not to use:** one-line answers (**Input / Text**).\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof TextArea>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Filled: Story = { name: "Filled", args: { "State": "Filled" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };
export const Success: Story = { name: "Success", args: { "State": "Success" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Focus", "Filled", "Error", "Disabled", "Success"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <TextArea {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
