// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { Toggle } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Toggle",
  component: Toggle,
  tags: ['autodocs', 'tier-atom'],
  argTypes: {
  "Value": {
    "control": "inline-radio",
    "options": [
      "Off",
      "On"
    ],
    "description": "Figma variant property `Value`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Off"
      }
    }
  },
  "State": {
    "control": "inline-radio",
    "options": [
      "Default",
      "Hover",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Label"
      }
    }
  },
  "Show Label": {
    "control": "boolean",
    "description": "Figma boolean property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "true"
      }
    }
  }
},
  args: {"Value": "Off", "State": "Default", "Label": "Label", "Show Label": true},
  parameters: {
    figma: { name: "Toggle", page: "➜ Toggles", tier: "Atom", order: 1 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2869" },
    docs: { description: { component: "**Figma:** `Toggle` on page `➜ Toggles` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=5-2869)\n\n**Tier:** Atom\n\n**Use:** A setting that applies at once (appointment reminders). Inside a saved form use Checkbox.\n\n**Figma description:**\n\n> Atom. Purpose: switch a setting on or off with immediate effect (appointment reminders, show cancelled visits).  \n> Usage rules: the change applies at once, no Save button; the label names the setting (\"Email reminders\"), not the action; for choices submitted with a form use Checkbox.  \n> Accessibility: track 44x24 with a 16px knob; the Off track has a color/border/input border (3.7:1) so it is visible on dark; state is shown by knob position and color, never color alone; Focus shows focus-ring-offset; role=\"switch\" in code.  \n\n**When to use:** settings that apply at once (appointment reminders, email notifications, show cancelled visits).\n\n**When not to use:** inside a form saved with a button (**Checkbox**); to choose between two named options (**Radio** or **Tabs / Bar** Segmented).\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof Toggle>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Off: Story = { name: "Off", args: { "Value": "Off" } };
export const On: Story = { name: "On", args: { "Value": "On" } };
export const StateDefault: Story = { name: "State=Default", args: { "State": "Default" } };
export const StateHover: Story = { name: "State=Hover", args: { "State": "Hover" } };
export const StateFocus: Story = { name: "State=Focus", args: { "State": "Focus" } };
export const StateDisabled: Story = { name: "State=Disabled", args: { "State": "Disabled" } };

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-col">
      {["Off", "On"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">Value={x}</div>
          <div className="sb-row">{["Default", "Hover", "Focus", "Disabled"].map((y) => <Toggle key={y} {...args} {...{ "Value": x, "State": y } as any} />)}</div>
        </div>
      ))}
    </div>
  ),
};
