// Generated by tools/storybook_stories.py from data/component-registry.json. Do not edit by hand;
// change the registry or src/components and regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { UploadField } from '../../components/FormElements';

const meta = {
  title: "Form Elements/Upload Field",
  component: UploadField,
  tags: ['!autodocs', 'tier-molecule'],
  argTypes: {
  "State": {
    "control": "select",
    "options": [
      "Default",
      "Hover",
      "Uploading",
      "Uploaded",
      "Error",
      "Focus",
      "Disabled"
    ],
    "description": "Figma variant property `State`",
    "table": {
      "category": "Figma variants",
      "defaultValue": {
        "summary": "Default"
      }
    }
  },
  "Label": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "Lab report"
      }
    }
  },
  "Format Hint": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "PDF, JPG or PNG, up to 10 MB"
      }
    }
  },
  "Error Message": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "This file is larger than 10 MB"
      }
    }
  },
  "File Name": {
    "control": "text",
    "description": "Figma text property",
    "table": {
      "category": "Figma properties",
      "defaultValue": {
        "summary": "blood-test-march.pdf"
      }
    }
  }
},
  args: {"State": "Default", "Label": "Lab report", "Format Hint": "PDF, JPG or PNG, up to 10 MB", "Error Message": "This file is larger than 10 MB", "File Name": "blood-test-march.pdf"},
  parameters: {
    figma: { name: "Upload Field", page: "➜ Input Fields and Dropdown", tier: "Molecule", order: 2 },
    design: { type: 'figma', url: "https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-4013" },
    docs: { description: { component: "**Figma:** `Upload Field` on page `➜ Input Fields and Dropdown` (Form Elements). [Open in Figma](https://www.figma.com/design/m0G6wKSbVhgqWutfmt7vFU/NEW-PROJECT-Design-system?node-id=7-4013)\n\n**Tier:** Molecule\n\n**Use:** Attach files to a record (lab reports, referral letters, ID scans).\n\n**Figma description:**\n\n> Molecule (Upload Icon, Button atom, Icon Button atom, progress). Purpose: attach files to a record (lab reports, referral letters, ID scans).  \n> Usage rules: say the allowed formats and size in the zone; Hover is the drag-over state; Uploading shows progress and a cancel Icon Button; Uploaded shows the file with a remove Icon Button; Error explains what to fix. One field per document type.  \n> Accessibility: the Browse Button is the keyboard path (drag and drop is optional); dashed border color/border/input (3.7:1); progress is announced in code; remove/cancel Icon Buttons need aria-labels.  \n\n**When to use:** lab reports, referral letters, ID scans on a patient record; one field per document type.\n\n**When not to use:** profile photos (Avatar Upload is out of scope for v1); many files at once (not built).\n\n**Built from:** `Icon/Upload`, `Button`, `Icon Button`, `Icon/File Text`, `Icon/Close`, `Icon/Delete`\n\nControls use the Figma variant and property names exactly. Switch the Figma modes (Semantic theme, Desktop/iPad/Mobile) from the toolbar." } },
  },
} satisfies Meta<typeof UploadField>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {};
export const Default: Story = { name: "Default", args: { "State": "Default" } };
export const Hover: Story = { name: "Hover", args: { "State": "Hover" } };
export const Uploading: Story = { name: "Uploading", args: { "State": "Uploading" } };
export const Uploaded: Story = { name: "Uploaded", args: { "State": "Uploaded" } };
export const Error: Story = { name: "Error", args: { "State": "Error" } };
export const Focus: Story = { name: "Focus", args: { "State": "Focus" } };
export const Disabled: Story = { name: "Disabled", args: { "State": "Disabled" } };

export const States: Story = {
  name: "States",
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Uploading", "Uploaded", "Error", "Focus", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <UploadField {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};

export const AllVariants: Story = {
  name: 'All variants',
  render: (args) => (
    <div className="sb-row">
      {["Default", "Hover", "Uploading", "Uploaded", "Error", "Focus", "Disabled"].map((x) => (
        <div key={x}>
          <div className="sb-cell-label ts-xs-medium">State={x}</div>
          <UploadField {...args} {...{ "State": x } as any} />
        </div>
      ))}
    </div>
  ),
};
